#!/usr/bin/env bash
# Prepare deploy/demo/seed from tenants/demo (L0–L1 only · no protocol runtime clutter)
# Run from repo root: bash deploy/demo/prepare-seed.sh
# Design: docs/org-os/demo-docker.md
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SEED="${ROOT}/deploy/demo/seed"
SRC="${ROOT}/tenants/demo"
TENANT_SEED="${SEED}/tenants/demo"

# L2 paths — never copy from local tenant into published seed (gitignore 実データ漏洩防止)
L2_REL_PATHS=(
  "data/finance/bank-accounts.yaml"
  "data/executive/stakeholders.yaml"
  "data/executive/calendar.yaml"
  "data/executive/tasks.yaml"
  "data/executive/one-on-ones.yaml"
  "data/executive/external-contacts.yaml"
  "data/org/operators.yaml"
)

strip_l2_from_seed() {
  for rel in "${L2_REL_PATHS[@]}"; do
    rm -f "${TENANT_SEED}/${rel}"
  done
}

write_demo_l1_stubs() {
  mkdir -p "${TENANT_SEED}/data/executive"
  cat > "${TENANT_SEED}/data/executive/stakeholders.yaml" <<'EOF'
stakeholders:
  - id: STK-001
    name: Known
    role: director
EOF
  cat > "${TENANT_SEED}/data/executive/calendar.yaml" <<'EOF'
events: []
EOF
  cat > "${TENANT_SEED}/data/executive/tasks.yaml" <<'EOF'
tasks: []
EOF
  cat > "${TENANT_SEED}/data/executive/one-on-ones.yaml" <<'EOF'
meetings: []
EOF
  cat > "${TENANT_SEED}/data/executive/external-contacts.yaml" <<'EOF'
contacts: []
EOF
}

rm -rf "${SEED}"
mkdir -p "${TENANT_SEED}"

cat > "${SEED}/orgos.yaml" <<'EOF'
# OrgOS workspace — demo Docker seed (do not use in production)
version: "1"
name: orgos-demo
EOF

# Core tenant config
for f in tenant.yaml modules.yaml standards.yaml regulations.yaml; do
  if [[ -f "${SRC}/${f}" ]]; then
    cp "${SRC}/${f}" "${TENANT_SEED}/${f}"
  fi
done

# Directory tree with content worth shipping (skip protocol inbox/outbox · chat threads · audit noise)
if rsync -a --delete \
  --exclude 'docs/protocol/' \
  --exclude 'docs/reports/audit-log/' \
  --exclude 'docs/reports/routing-queue/' \
  --exclude 'data/chat/' \
  --exclude 'data/protocol/' \
  --exclude '**/*.key' \
  --exclude '**/*secret*' \
  --exclude '**/guest-secrets.yaml' \
  --exclude 'data/finance/bank-accounts.yaml' \
  --exclude 'data/executive/stakeholders.yaml' \
  --exclude 'data/executive/calendar.yaml' \
  --exclude 'data/executive/tasks.yaml' \
  --exclude 'data/executive/one-on-ones.yaml' \
  --exclude 'data/executive/external-contacts.yaml' \
  --exclude 'data/org/operators.yaml' \
  "${SRC}/data" "${SRC}/docs" "${SRC}/rules" \
  "${TENANT_SEED}/" 2>/dev/null; then
  :
else
  # fallback without rsync
  for d in data docs rules; do
    if [[ -d "${SRC}/${d}" ]]; then
      mkdir -p "${TENANT_SEED}/${d}"
      cp -R "${SRC}/${d}/." "${TENANT_SEED}/${d}/"
    fi
  done
  rm -rf \
    "${TENANT_SEED}/docs/protocol" \
    "${TENANT_SEED}/docs/reports/audit-log" \
    "${TENANT_SEED}/docs/reports/routing-queue" \
    "${TENANT_SEED}/data/chat" \
    "${TENANT_SEED}/data/protocol" \
    2>/dev/null || true
  strip_l2_from_seed
fi

strip_l2_from_seed
write_demo_l1_stubs

# Ensure empty dirs exist for runtime writers
mkdir -p \
  "${TENANT_SEED}/docs/protocol/inbox" \
  "${TENANT_SEED}/docs/protocol/outbox" \
  "${TENANT_SEED}/docs/reports/audit-log" \
  "${TENANT_SEED}/docs/reports/routing-queue/queue" \
  "${TENANT_SEED}/data/chat/threads"

# Placeholder operators example only — demo auth is off
if [[ -f "${ROOT}/tenants/_template/data/org/operators.yaml.example" ]]; then
  mkdir -p "${TENANT_SEED}/data/org"
  cp "${ROOT}/tenants/_template/data/org/operators.yaml.example" \
    "${TENANT_SEED}/data/org/operators.yaml.example"
fi

cat > "${SEED}/README.md" <<'EOF'
# Demo workspace seed

Generated by `deploy/demo/prepare-seed.sh`.  
Copied into `/workspace` on first container start. **L2/L3 and production secrets must not appear here.**
EOF

echo "✓ Seed prepared at ${SEED}"
du -sh "${SEED}" || true
