/**
 * Known direct canonical writes not yet routed through wrapCanonicalWrite / guarded writers.
 * New hits fail scripts/check-canonical-writes.ts — migrate or add here with justification.
 * Generated/updated by: node --import tsx scripts/check-canonical-writes.ts --write
 */
export type CanonicalWriteBaselineEntry = {
  file: string;
  line: number;
  symbol: string;
  note: string;
};

export const CANONICAL_WRITE_BASELINE: CanonicalWriteBaselineEntry[] = [
  { file: "src/commands/finances-close.ts", line: 170, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/finances-close.ts", line: 331, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/locale-jurisdiction.ts", line: 232, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/migrate.ts", line: 38, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/operator-registry.ts", line: 93, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/operator-registry.ts", line: 140, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/operator.ts", line: 60, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/platform-scaffold.ts", line: 105, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/protocol.ts", line: 1890, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/wire-gateway.ts", line: 143, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/wire-gateway.ts", line: 222, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/commands/workspace.ts", line: 30, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/agent-capability-sync.ts", line: 102, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/agent-docs-sync.ts", line: 361, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/agent-docs-sync.ts", line: 362, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/agent-docs-sync.ts", line: 363, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/agent-portability.ts", line: 234, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/agent-workspace.ts", line: 57, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/agent-workspace.ts", line: 60, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/agent-workspace.ts", line: 93, symbol: "cpSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/aia/scheduler.ts", line: 297, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/broker.ts", line: 173, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/certification-workflow.ts", line: 78, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-chain.ts", line: 556, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-export.ts", line: 322, symbol: "cpSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-export.ts", line: 325, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-export.ts", line: 331, symbol: "cpSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-export.ts", line: 334, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-export.ts", line: 344, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-export.ts", line: 348, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-export.ts", line: 353, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-export.ts", line: 357, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-export.ts", line: 384, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-signing.ts", line: 105, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/company-events-signing.ts", line: 157, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/console-auth/session-store.ts", line: 45, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/context-manifest.ts", line: 271, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/context-manifest.ts", line: 272, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/correspondence/gmail-oauth.ts", line: 38, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/correspondence/gmail-oauth.ts", line: 112, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/correspondence/gmail-receive-sync.ts", line: 113, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/correspondence/mail-config.ts", line: 80, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/correspondence/mail-receive-sync.ts", line: 130, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/correspondence/mail-send.ts", line: 228, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/document-io.ts", line: 106, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/document-io.ts", line: 147, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/document-io.ts", line: 154, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/document-io.ts", line: 212, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/document-io.ts", line: 214, symbol: "renameSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/finance/tax-filing-docs.ts", line: 203, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/finance/tax-filing-docs.ts", line: 204, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/folder-housekeeping.ts", line: 209, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/hub/federation.ts", line: 55, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/hub/merkle-anchor.ts", line: 97, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/hub/signing.ts", line: 28, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/inspection-workflow.ts", line: 140, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/integrations.ts", line: 55, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/invoice-email.ts", line: 206, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/invoice-email.ts", line: 209, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/invoice-email.ts", line: 212, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/jsonl-store.ts", line: 13, symbol: "appendFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/jsonl-store.ts", line: 59, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/latex-compile.ts", line: 137, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/mcp/audit.ts", line: 38, symbol: "appendFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/module-compliance-onboard.ts", line: 270, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/module-compliance-onboard.ts", line: 303, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/operator-commands/execute.ts", line: 31, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/operator-policy.ts", line: 115, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/operator-policy.ts", line: 170, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/operator-policy.ts", line: 178, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/operator-policy.ts", line: 266, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/operator-policy.ts", line: 449, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/operator-policy.ts", line: 464, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/operator-policy.ts", line: 471, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/operator-runtime/telemetry.ts", line: 56, symbol: "appendFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/org/budget-delegation.ts", line: 251, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/org/human-approval-context.ts", line: 105, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/org/instruction-audit.ts", line: 48, symbol: "appendFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/org/operator-keys.ts", line: 34, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/org/settlement-stepup.ts", line: 150, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/org/settlement-stepup.ts", line: 151, symbol: "renameSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/pdf-esign/adapters/digidoc.ts", line: 24, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/pdf-esign/digidoc-sidecar-client.ts", line: 63, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/pdf-esign/digidoc-sidecar-client.ts", line: 64, symbol: "renameSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/audit-chain.ts", line: 103, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/community-export.ts", line: 27, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/community-export.ts", line: 40, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/community-export.ts", line: 45, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/community-export.ts", line: 51, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/community-gmail-bind.ts", line: 42, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/dev-server-tls.ts", line: 28, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/email-wire-deliver.ts", line: 221, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/org-cert-witness.ts", line: 143, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/outbox-provenance.ts", line: 23, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/protocol-api-server.ts", line: 222, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/signing.ts", line: 33, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/signing.ts", line: 92, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/signing.ts", line: 96, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/test-suite-status.ts", line: 33, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/test-suite-status.ts", line: 43, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/tls-pki.ts", line: 42, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/tls-pki.ts", line: 194, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/tls-pki.ts", line: 254, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/tls-pki.ts", line: 258, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/transport.ts", line: 466, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/transport/inbound.ts", line: 11, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/trusted-hubs-sync.ts", line: 174, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/wire-live-verify.ts", line: 39, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/wire-live-verify.ts", line: 233, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/wire-trust-registry-sync.ts", line: 189, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/wire-trust-registry-sync.ts", line: 281, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/witness-attestation-build.ts", line: 50, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/witness-trust.ts", line: 125, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/witness-trust.ts", line: 208, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/witness-trust.ts", line: 235, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/protocol/witness-trust.ts", line: 272, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/receipt-qr.ts", line: 364, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/receipt-qr.ts", line: 547, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/receipt-qr.ts", line: 548, symbol: "renameSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/receipt-qr.ts", line: 649, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/receipt-qr.ts", line: 967, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/receipt-qr.ts", line: 990, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/regulations.ts", line: 269, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/regulations.ts", line: 295, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/scheduling-coordination/inject-schedule-reply-mail.ts", line: 63, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/scheduling-coordination/rehearsal-mail-overlay.ts", line: 26, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/scheduling-coordination/rehearsal-mail-overlay.ts", line: 31, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/scheduling-coordination/rehearsal-mail-overlay.ts", line: 41, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/scheduling-coordination/rehearsal-mail-overlay.ts", line: 46, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/steward-chat/audit.ts", line: 38, symbol: "appendFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/steward-chat/chat-thread.ts", line: 84, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/steward-chat/chat-thread.ts", line: 146, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/sync-csv.ts", line: 28, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-document-zones.ts", line: 104, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-document-zones.ts", line: 144, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-document-zones.ts", line: 150, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-init.ts", line: 51, symbol: "cpSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-init.ts", line: 141, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-init.ts", line: 155, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-init.ts", line: 290, symbol: "cpSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-init.ts", line: 321, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-scaffold.ts", line: 12, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-scaffold.ts", line: 44, symbol: "cpSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-scaffold.ts", line: 81, symbol: "cpSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-setup-wizard.ts", line: 92, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/tenant-setup-wizard.ts", line: 202, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/vault.ts", line: 148, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/auth/passkey-bootstrap.ts", line: 70, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/auth/passkey-bootstrap.ts", line: 71, symbol: "renameSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/auth/passkey-field-check-record.ts", line: 99, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/auth/webauthn-challenge-store.ts", line: 220, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/auth/webauthn-challenge-store.ts", line: 221, symbol: "renameSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/auth/webauthn-env-sign-count.ts", line: 40, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/auth/webauthn-env-sign-count.ts", line: 41, symbol: "renameSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/auth/webauthn-store.ts", line: 87, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/auth/webauthn-store.ts", line: 88, symbol: "renameSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-console/process.ts", line: 31, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire-gateway/nonce-ledger.ts", line: 35, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "src/lib/wire/gov-gateway/sandbox.ts", line: 178, symbol: "copyFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/jurisdiction-packs/JP/modules/jp_corporate_registration/cli/lib.ts", line: 1276, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/jurisdiction-packs/JP/modules/jp_corporate_registration/cli/lib.ts", line: 1398, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/jurisdiction-packs/JP/modules/jp_permit_application/cli/application-lib.ts", line: 393, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/jurisdiction-packs/JP/modules/jp_permit_application/cli/application-lib.ts", line: 1095, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/jurisdiction-packs/JP/modules/jp_permit_registry/cli/application-lib.ts", line: 176, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/jurisdiction-packs/JP/modules/jp_permit_registry/cli/application-lib.ts", line: 451, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/modules/hospitality/cli/guest-register.ts", line: 340, symbol: "appendFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/modules/hospitality/cli/guest-register.ts", line: 383, symbol: "appendFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/modules/language_bridge/cli/commands.ts", line: 58, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
  { file: "steward/modules/travel_booking/cli/lib.ts", line: 379, symbol: "writeFileSync", note: "pending migration to wrapCanonicalWrite / writeYamlFile / writeTrackedFile" },
];

export function canonicalWriteBaselineKey(entry: CanonicalWriteBaselineEntry): string {
  return `${entry.file}:${entry.line}:${entry.symbol}`;
}

export function countCanonicalWriteBaselineEntries(): number {
  return CANONICAL_WRITE_BASELINE.length;
}

/** Files that implement or bootstrap the guard — not tenant canonical writes. */
export const CANONICAL_WRITE_SCAN_SKIP_FILES = new Set([
  "src/lib/utils.ts",
  "src/lib/yaml-atomic.ts",
  "src/lib/org/fs-guard/guarded-write.ts",
  "src/lib/org/fs-guard/lease.ts",
  "src/lib/org/fs-guard/store.ts",
  "src/lib/org/fs-guard/policy.ts",
  "src/lib/org/fs-guard/write-hook.ts",
  "src/lib/org/fs-guard/canonical-write-baseline.ts",
  "src/lib/operator-runtime/shell.ts",
  "scripts/check-canonical-writes.ts",
]);

export const CANONICAL_WRITE_SCAN_SKIP_DIRS = new Set([
  "node_modules",
  "tests",
  "dist",
  "apps/steward-chat/dist",
  "apps/wire-console/dist",
]);

export const CANONICAL_WRITE_SYMBOLS = [
  "writeFileSync",
  "appendFileSync",
  "copyFileSync",
  "cpSync",
  "renameSync",
] as const;
