import { defineCopy } from "./define-copy";

export const SHELL_COPY = defineCopy(
  {
    nav: "Operator Console",
    executive: "経営",
    finance: "財務",
    business: "業務",
    organization: "組織",
    aiTeam: "AIチーム",
    connections: "連携",
    ledger: "帳簿",
    yojitsu: "予実",
    torihiki: "取引",
    wire: "Wire",
    org: "組織図",
    approvals: "承認",
    customers: "顧客管理",
    runs: "実行状況",
    agents: "エージェント",
    secretary: "秘書",
    steward: "スチュワード",
    settings: "設定",
    signOut: "サインアウト",
    operatorTitle: "ログイン中のオペレータ ID・承認者・実行モード",
    checkingAuth: "認証確認中…",
    signedOut: "未ログイン",
    prodAuth: "本番認証",
  },
  {
    nav: "Operator Console",
    executive: "Home",
    finance: "Finance",
    business: "Operations",
    organization: "Organization",
    aiTeam: "AI team",
    connections: "Connections",
    ledger: "Ledger",
    yojitsu: "Budget",
    torihiki: "Transactions",
    wire: "Wire",
    org: "Org chart",
    approvals: "Approvals",
    customers: "Customers",
    runs: "Run status",
    agents: "Agents",
    secretary: "Secretary",
    steward: "Steward",
    settings: "Settings",
    signOut: "Sign out",
    operatorTitle: "Signed-in operator ID, approver, and mode",
    checkingAuth: "Checking sign-in…",
    signedOut: "Signed out",
    prodAuth: "Production auth",
  },
);

export const SESSION_COPY = defineCopy(
  {
    operator: "オペレータ",
    approver: "承認者",
    devMode: "開発モード",
    prodMode: "本番モード",
  },
  {
    operator: "Operator",
    approver: "Approver",
    devMode: "Dev mode",
    prodMode: "Production mode",
  },
);

export const AUTH_COPY = defineCopy(
  {
    titleMac: "この Mac で入る",
    titleOperator: "オペレーターとして入る",
    titleSession: "オペレーター認証",
    sessionNeeded: "セッションが必要です",
    loading: "読み込み中…",
    checking: "認証を確認中…",
    leadPasskeyAndPassword: "PassKey か、ID とパスワードで入れます。",
    leadPasskeyOnly: "登録したログイン PassKey で入ります。",
    leadGeneric: "コンソールに入るための認証です。",
    orPassword: "ID・パスワードで入る",
    passwordWhenPasskeyUnavailable:
      "このブラウザでは PassKey を使えません。下のオペレーター ID とパスワードで入れてください。",
    touchIdEnter: "Touch ID で入る",
    touchIdRegister: "Touch ID で登録",
    enter: "入る",
    checkingBusy: "確認中…",
    sessionPersistFailed:
      "ログインは成功しましたが、セッションを保持できませんでした。ID とパスワードで入り直してください。",
    registering: "登録中…",
    password: "パスワード",
    operator: "オペレーター",
    approver: "承認者",
    oidcToken: "OIDC トークン",
    prodToken: "本番トークン",
    passkeyLoginLabel: "PassKey ログイン",
    devLoginLabel: "開発ログイン",
    useWireInstead: "この画面では入れません。",
    useWireLink: "Wire",
    useWireAfter: " から Touch ID で入ってください。",
    thisMac: "この Mac",
    login: "ログイン",
    loginLead: "Touch ID でコンソールに入ります。",
    loginStatusReady: "使える",
    loginStatusPending: "まだ",
    communityFirstTitle: "PassKey 設定の前に Community でログイン",
    communityFirstLead:
      "Community で SSO ログインしたあと、このページで Touch ID 用 PassKey を登録します。",
    macLead:
      "Touch ID でコンソールに入ります。決済 PassKey はログイン後、設定から登録します。",
    operatorAndApprover: "オペレーターと承認者",
    displayNamePlaceholder: "表示名",
    handoffHint: "初回登録は Community でログインしたあと、PassKey 設定から行います。",
    communityGoogle: "Community で Google ログイン",
    openPasskeySettingsBefore: "このコンソールの ",
    openPasskeySettingsLink: "PassKey 設定",
    openPasskeySettingsAfter: " を開く",
    bootstrapStep: "CLI で発行した bootstrap トークンを入力し、Touch ID で登録",
    communityEnter: "Community で入る",
    consoleLoginTitle: "会社コンソールに入る",
    consoleLoginLead:
      "本鍵は Community の会社 Google サインインです。PassKey でも、ID とパスワードでも入れます。",
    navOverview: "Overview",
    navCommunity: "Community",
    noLoginKey: "ログイン用の鍵がまだありません。管理者に登録の許可を依頼してください。",
    registerAnother: "別の鍵を登録",
  },
  {
    titleMac: "Sign in on this Mac",
    titleOperator: "Sign in as operator",
    titleSession: "Operator sign-in",
    sessionNeeded: "A session is required",
    loading: "Loading…",
    checking: "Checking sign-in…",
    leadPasskeyAndPassword: "Sign in with a PassKey, or with operator ID and password.",
    leadPasskeyOnly: "Sign in with your registered login PassKey.",
    leadGeneric: "Sign in to open the console.",
    orPassword: "Sign in with ID and password",
    passwordWhenPasskeyUnavailable:
      "PassKey is not available in this browser. Sign in below with operator ID and password.",
    touchIdEnter: "Sign in with Touch ID",
    touchIdRegister: "Register with Touch ID",
    enter: "Sign in",
    checkingBusy: "Checking…",
    sessionPersistFailed:
      "Sign-in succeeded but the session cookie could not be stored. Sign in again with ID and password.",
    registering: "Registering…",
    password: "Password",
    operator: "Operator",
    approver: "Approver",
    oidcToken: "OIDC token",
    prodToken: "Production token",
    passkeyLoginLabel: "PassKey sign-in",
    devLoginLabel: "Development sign-in",
    useWireInstead: "You cannot sign in on this screen. Use Touch ID from ",
    useWireLink: "Wire",
    useWireAfter: ".",
    thisMac: "This Mac",
    login: "Sign-in",
    loginLead: "Sign in to the console with Touch ID.",
    loginStatusReady: "Ready",
    loginStatusPending: "Not yet",
    communityFirstTitle: "Sign in to Community before PassKey setup",
    communityFirstLead:
      "After Community SSO, register the Touch ID PassKey on this page.",
    macLead:
      "Sign in with Touch ID. Register the settlement PassKey from Settings after sign-in.",
    operatorAndApprover: "Operator and approver",
    displayNamePlaceholder: "Display name",
    handoffHint: "First registration is done from PassKey settings after Community sign-in.",
    communityGoogle: "Sign in to Community with Google",
    openPasskeySettingsBefore: "Open ",
    openPasskeySettingsLink: "PassKey settings",
    openPasskeySettingsAfter: " on this console",
    bootstrapStep: "Paste the CLI bootstrap token and register with Touch ID",
    communityEnter: "Continue to Community",
    consoleLoginTitle: "Open your company console",
    consoleLoginLead:
      "Your primary key is company Google sign-in via Community. You can also sign in with a PassKey, or with operator ID and password.",
    navOverview: "Overview",
    navCommunity: "Community",
    noLoginKey: "No login key yet. Ask an administrator to allow registration.",
    registerAnother: "Register another key",
  },
);

export const SETTINGS_COPY = defineCopy(
  {
    title: "設定",
    language: "言語",
    languageLegend: "表示言語",
    languageJa: "日本語",
    languageEn: "English",
    appearance: "外観",
    appearanceLegend: "スタイル",
    light: "ライト",
    lightHint: "明るい背景（oorgos.org と同じ）",
    dark: "ダーク",
    darkHint: "暗い場所向けの背景",
    system: "システムデフォルト",
    systemHint: "この端末のライト／ダーク設定に合わせる",
    loginPasskey: "ログイン PassKey（Mac Touch ID）",
    settlementPasskey: "決済 PassKey（iPhone）",
    off: "オフ",
    none: "未登録",
    loading: "読み込み中",
    loadingEllipsis: "読み込み中…",
    webauthnOffHere:
      "この環境では WebAuthn がオフです。本番（または WebAuthn 有効時）に同じ場所で発行します。",
    settlementOffHere: "この環境では発行できません。本番では同じ「設定」から発行します。",
    webauthnDisabled: "この環境では WebAuthn が有効ではありません。",
    companySetup: "会社セットアップ",
    companySetupLead: "会社情報・Passkey・初回仕訳を完了して帳簿を使えるようにします。",
    companySetupOpen: "セットアップを開く",
    accountAdmin: "アカウント管理",
    accountAdminLead: "プラン・招待・課金状況を確認します。",
    accountAdminOpen: "アカウントを開く",
  },
  {
    title: "Settings",
    language: "Language",
    languageLegend: "Display language",
    languageJa: "日本語",
    languageEn: "English",
    appearance: "Appearance",
    appearanceLegend: "Style",
    light: "Light",
    lightHint: "Bright background, matching oorgos.org",
    dark: "Dark",
    darkHint: "Dim background for low light",
    system: "System default",
    systemHint: "Follow this device’s light or dark setting",
    loginPasskey: "Login PassKey (Mac Touch ID)",
    settlementPasskey: "Settlement PassKey (iPhone)",
    off: "Off",
    none: "None",
    loading: "Loading",
    loadingEllipsis: "Loading…",
    webauthnOffHere: "WebAuthn is off here. Issue the key in this same place when WebAuthn is on.",
    settlementOffHere: "Cannot be issued in this environment. Production uses this same Settings page.",
    webauthnDisabled: "WebAuthn is not enabled in this environment.",
    companySetup: "Company setup",
    companySetupLead: "Complete company profile, Passkey, and the first journal entry to use the ledger.",
    companySetupOpen: "Open setup",
    accountAdmin: "Account admin",
    accountAdminLead: "Review plan, invites, and billing status.",
    accountAdminOpen: "Open account",
  },
);

export const PASSKEY_COPY = defineCopy(
  {
    loginLead: "Touch ID でコンソールに入り直す鍵です。",
    settlementLead:
      "高額承認用です。ブラウザの QR を iPhone のカメラで読み、Bluetooth をオンにしてください。",
    checkingTouchId: "Touch ID を確認中…",
    addAnotherKey: "別の鍵を追加",
    showingIphoneQr: "iPhone の QR を表示中…",
    registerIphone: "iPhone で登録",
    registerAnotherIphone: "別の iPhone で登録",
    colKind: "種別",
    colDevice: "端末",
    colRegistered: "登録日時",
    colId: "ID",
    colAction: "操作",
    purposeLogin: "ログイン",
    purposeSettlement: "決済",
    revoke: "登録解除",
    revoking: "解除中…",
    managedByEnv: "環境変数",
    emptyLogin: "ログイン用の PassKey はまだありません。",
    emptySettlement: "決済 PassKey は未登録です。",
    extraLoginHint: "追加のログイン鍵は管理者が有効にしたときだけ登録できます。",
    settlementCallout: "決済 PassKey の発行は設定から行います。",
    settlementCalloutLink: "設定の PassKey 発行",
    settlementRegistered: "登録済みです。高額承認のとき、この Mac のブラウザが QR を表示します。",
    settlementHint: "登録中は Mac の Bluetooth をオンにし、iPhone を近くに置いてください。",
    bootstrapHint: "初回登録: CLI でトークンを発行 → 下欄に貼り付け → Touch ID で登録",
    bootstrapToken: "Bootstrap トークン",
    deviceThisMac: "この Mac（Touch ID）",
    deviceIphoneSettlement: "iPhone（決済）",
    deviceExternal: "iPhone / 外部",
    confirmRevoke: (label: string, shortId: string) =>
      `${label} の PassKey（${shortId}）を登録解除しますか？`,
    count: (n: number) => `${n}件`,
  },
  {
    loginLead: "The key that lets you return to the console with Touch ID.",
    settlementLead:
      "For high-value approvals. Scan the browser QR with iPhone and keep Bluetooth on.",
    checkingTouchId: "Confirming Touch ID…",
    addAnotherKey: "Add another key",
    showingIphoneQr: "Showing the iPhone QR…",
    registerIphone: "Register with iPhone",
    registerAnotherIphone: "Register another iPhone",
    colKind: "Type",
    colDevice: "Device",
    colRegistered: "Registered",
    colId: "ID",
    colAction: "Action",
    purposeLogin: "Login",
    purposeSettlement: "Settlement",
    revoke: "Remove",
    revoking: "Removing…",
    managedByEnv: "Environment",
    emptyLogin: "No login PassKey yet.",
    emptySettlement: "No settlement PassKey yet.",
    extraLoginHint: "Additional login keys can be registered only when an administrator enables them.",
    settlementCallout: "Issue the settlement PassKey from Settings.",
    settlementCalloutLink: "Issue PassKey in Settings",
    settlementRegistered:
      "Registered. For high-value approval, this Mac’s browser shows the QR.",
    settlementHint: "Keep Mac Bluetooth on and keep the iPhone nearby while registering.",
    bootstrapHint: "First registration: mint a CLI token → paste it below → register with Touch ID",
    bootstrapToken: "Bootstrap token",
    deviceThisMac: "This Mac (Touch ID)",
    deviceIphoneSettlement: "iPhone (settlement)",
    deviceExternal: "iPhone / external",
    confirmRevoke: (label: string, shortId: string) =>
      `Remove the PassKey for ${label} (${shortId})?`,
    count: (n: number) => String(n),
  },
);

export const SETTLEMENT_COPY = defineCopy(
  {
    title: "iPhone の PassKey で承認",
    done: "承認できました。",
    failed: "承認できませんでした。",
    ready: "ログイン（Touch ID）とは別の決済 PassKey で承認します。",
    waiting: "ブラウザの PassKey シートを開いています。iPhone のカメラで QR を読んでください。",
    notLoginKey: "Mac の Touch ID ログイン鍵では承認できません。",
    bluetoothOn: "Mac と iPhone の Bluetooth をオンにしてください。",
    retryHint: "Bluetooth がオフ、または距離が遠いと失敗します。もう一度試してください。",
    amount: "金額",
    subject: "件名",
    start: "iPhone で承認を開始",
    again: "もう一度",
    cancel: "キャンセル",
    close: "閉じる",
  },
  {
    title: "Approve with iPhone PassKey",
    done: "Approved.",
    failed: "Approval failed.",
    ready: "This uses your settlement PassKey — not the Mac Touch ID login key.",
    waiting: "Opening the browser PassKey sheet. Scan the QR with the iPhone camera.",
    notLoginKey: "The Mac Touch ID login key cannot approve this action.",
    bluetoothOn: "Turn on Bluetooth on the Mac and iPhone.",
    retryHint: "This fails if Bluetooth is off or the devices are far apart. Try again.",
    amount: "Amount",
    subject: "Subject",
    start: "Start iPhone approval",
    again: "Try again",
    cancel: "Cancel",
    close: "Close",
  },
);
