import { defineCopy } from "@ops-shared/define-copy";

export const OPS_PAGES_COPY = defineCopy(
  {
    analyticsTitle: "分析ダッシュボード",
    analyticsLead: "KPI スコアカードとデータ品質。",
    loading: "読み込み中…",
    summary: "サマリー",
    kpiGreen: "正常",
    kpiAmber: "注意",
    kpiRed: "要対応",
    kpiUnknown: "不明",
    dataQuality: "データ品質",
    momPresent: "前月比あり",
    attainment: "目標達成率",
    noMetrics: "指標がまだありません",
    noMetricsHint: "目標を置くと、ここに達成率が出ます。",
    kpiList: "KPI 一覧",
    colRag: "RAG",
    colMetric: "指標",
    colActual: "実測",
    colTarget: "目標",
    colMom: "前月比",
    ledgerTitle: "帳簿",
    ledgerLead:
      "試算表・貸借対照表・仕訳・補助元帳と、月次起票・消込・納付の操作です。",
    asOf: "基準日",
    opsMonth: "操作月",
    reload: "再読込",
    asOfValue: (date: string) => `基準日 ${date}`,
    monthlyPost: "月次起票",
    postDepreciation: "減価償却+月次損益",
    postPayroll: "給与支払",
    periodLock: "期間ロック",
    noLockHistory: "ロック履歴なし",
    colMonth: "月",
    colStatus: "状態",
    colOperator: "操作者",
    colWhen: "日時",
    lock: "ロック",
    unlockReason: "解除理由",
    unlock: "解除",
    taxBalances: "税・納付残高",
    colAccount: "科目",
    colName: "名称",
    colBalance: "残高",
    remittanceCalendar: "納付カレンダー",
    noRemittance: "納付対象のカレンダー行なし",
    colDeadline: "期限",
    colContent: "内容",
    colEstimate: "概算",
    remittanceJournal: "納付仕訳",
    monthlyReconcile: (month: string) => `月次突合 ${month}`,
    glActive: "GL 稼働 あり",
    glInactive: "GL 稼働 なし",
    matched: "一致",
    unmatched: "差異あり",
    colKind: "区分",
    colDelta: "差額",
    balanceSheet: "貸借対照表",
    cashFlow: "キャッシュ・フロー計算書",
    cashFlowMethod: (method: string) => `方式: ${method}`,
    cashFlowOperating: "営業活動",
    cashFlowInvesting: "投資活動",
    cashFlowFinancing: "財務活動",
    cashFlowNetChange: "現金増減",
    cashFlowBegin: "期首現金",
    cashFlowEnd: "期末現金",
    cashFlowReconciled: "現金残高と一致",
    cashFlowUnreconciled: "現金残高と不一致",
    downloadCashFlowCsv: "CF CSV",
    assets: "資産",
    liabilities: "負債",
    equity: "純資産",
    netIncome: "当期純利益",
    balanced: "均衡",
    unbalanced: "不均衡",
    priorCompare: "前期比較",
    priorAsOf: (date: string) => `前期末日 ${date}`,
    colItem: "項目",
    colCurrent: "当期",
    colPrior: "前期",
    colDiff: "差",
    revenue: "売上高",
    netProfit: "純利益",
    ledgerExport: "帳簿エクスポート",
    ledgerExportLead: "仕訳・試算表・科目内訳を CSV でダウンロードします。",
    downloadJournalCsv: "仕訳 CSV",
    downloadTrialBalanceCsv: "試算表 CSV",
    downloadAccountBreakdownCsv: "科目内訳 CSV",
    denchoSearch: "電子帳簿検索",
    denchoSearchLead: "日付・摘要で仕訳を検索します。",
    denchoFrom: "開始日",
    denchoTo: "終了日",
    denchoDescription: "摘要に含む",
    denchoRun: "検索",
    denchoNoHits: "該当なし",
    denchoHits: (n: number) => `${n} 件`,
    bankReconcile: "銀行消込",
    unmatchedCount: (n: number) => `未消込 ${n} 件`,
    noBankProposals: "承認候補なし（CLI `jp bank reconcile propose` も可）",
    colBankLine: "銀行明細",
    colArAp: "AR/AP",
    colAmount: "金額",
    colConfidence: "確度",
    approveMatch: "承認消込",
    colLine: "明細",
    colDate: "日付",
    colDirection: "向き",
    trialBalance: "試算表",
    debit: "借方",
    credit: "貸方",
    recentJournals: "最近の仕訳",
    colId: "ID",
    colMemo: "摘要",
    reverse: "逆仕訳",
    subsidiary: (code: string, name: string) => `補助元帳 ${code} ${name}`,
    control: "統制",
    colCounterparty: "相手先",
    arReceipt: "入金消込",
    apPayment: "支払消込",
    unpostedMonths: "未計上月（予実差異）",
    yen: (n: string) => `${n} 円`,
    runsTitle: "実行状況",
    runsLead: "いま動いている作業の進み具合です。",
    activePlans: "進行中の計画",
    noActive: "進行中の作業はありません",
    noActiveHint: "新しい作業が始まると、ここに進み具合が並びます。スチュワードに依頼すると計画がここに並びます。",
    allPlans: "すべての計画",
    filterAll: "すべて",
    filterAttention: "要対応のみ",
    filterAgent: "担当エージェント",
    filterWorkKind: "作業種別",
    viewIncomplete: "未完了",
    viewCompleted: "完了",
    viewAll: "すべて",
    groupByPlan: "計画",
    groupByAgent: "担当",
    groupByWorkKind: "種別",
    groupByDue: "期限",
    groupLabel: "グループ",
    hideEmpty: "空を隠す",
    completedPlans: "完了済みの計画",
    completeTask: "このタスクを完了",
    reopenTask: "完了を元に戻す",
    completeBusy: "完了中…",
    reopenBusy: "再開中…",
    confirmComplete: (title: string) => `${title} を完了にします。よろしいですか？`,
    confirmReopen: (title: string) => `${title} を未完了に戻します。よろしいですか？`,
    dueOverdue: "期限切れ",
    dueToday: "今日",
    dueSoon: "近日",
    dueLater: "以降",
    dueNone: "期限なし",
    columnAttention: "要対応",
    columnTodo: "未着手",
    columnWaiting: "待ち",
    columnActive: "実行中",
    columnDone: "完了",
    planProgress: (done: number, total: number) => `${done}/${total}`,
    planAttention: (n: number) => `要対応 ${n}`,
    workKindUnknown: "未分類",
    waitingOn: (title: string) => `待ち: ${title}`,
    cardDetail: "詳細",
    dueDate: "期限",
    assignee: "担当",
    blockedOn: "ブロック",
    workKind: "種別",
    closeDetail: "閉じる",
    completed: "完了済み",
    summaryOf: (id: string) => `サマリー · ${id}`,
    nodes: "ノード",
    colWave: "Wave",
    blockedDownstream: "ブロックされた下流",
    kpiReady: "実行可能",
    kpiBlocked: "ブロック",
    retryBusy: "再試行中…",
    retryFailed: "失敗を再試行",
    cancelBusy: "停止中…",
    cancelPending: "未実行を停止",
    openSteward: "Steward チャットで開く",
    statusPending: "待機",
    statusWaiting: "依存待ち",
    statusDispatched: "送出",
    statusRunning: "実行中",
    statusCompleted: "完了",
    statusFailed: "失敗",
    statusBlocked: "停止",
    confirmRetry: (id: string) => `${id}: 失敗ノードを待機に戻します。よろしいですか？`,
    confirmCancel: (id: string) => `${id}: 未実行ノードを停止します。よろしいですか？`,
    receiptIssueTitle: "領収書発行",
    receiptIssueLead:
      "適格請求書（または簡易）を署名付き QR 付きで発行します。発行者はテナントの法人番号から自動決定します。",
    issuerAuto: "発行者（自動）",
    issuerLoading: "発行者情報を読み込み中…",
    issuer: "発行者",
    registrationNo: "登録番号",
    corporateNo: "法人番号",
    issueInput: "発行入力",
    documentType: "文書種別",
    qualifiedInvoice: "適格請求書",
    qualifiedSimplified: "適格簡易請求書",
    transactionDate: "取引日",
    recipient: "宛名",
    recipientPlaceholder: "取引先名",
    lines: "明細",
    addLine: "行を追加",
    itemN: (n: number) => `品目${n}`,
    itemPlaceholder: "品目",
    qtyN: (n: number) => `数量${n}`,
    qtyPlaceholder: "数量",
    taxN: (n: number) => `税率${n}`,
    reduced: "軽減",
    exN: (n: number) => `税抜金額${n}`,
    exPlaceholder: "税抜",
    includingTax: "税込",
    delete: "削除",
    totalIncl: "合計（税込）",
    preview: "プレビュー",
    issuing: "処理中…",
    issue: "発行する",
    previewResult: "プレビュー結果",
    issueResult: "発行結果",
    copyLink: "リンクをコピー",
    downloadPdf: "PDF をダウンロード",
    defaultItem: "品目",
    errIssuer:
      "発行者情報を読み込めません（company.yaml の法人番号を確認してください）",
    errRecipient: "適格請求書では宛名を入力してください",
    errLines: "品目と税抜金額を1行以上入力してください",
    previewUpdated: "プレビューを更新しました（未永続）",
    confirmIssue: (total: string) =>
      `この内容で領収書を発行しますか？\n合計 ${total}\n発行後はレジストリに保存されます。`,
    issued: (id: string) => `${id} を発行しました`,
    linkCopied: "検証リンクをコピーしました",
    receiptTitle: "領収書の受け取り",
    receiptLead:
      "発行元が請求を受けたあと、承認すると receipt_id と digest のみを Wire で返します。金額・明細は入力も送信もしません。",
    approver: "承認者",
    noAmount: "金額は送らない",
    noApprovePerm: "承認する権限がありません",
    claimStatus: "claim ステータス",
    pending: "承認待ち",
    claimed: "承認済",
    rejected: "却下",
    all: "すべて",
    noClaims: "該当する claim はありません。",
    requestedAt: (when: string) => `要求 ${when}`,
    issuerLocalTotal: (amount: string) =>
      `発行元ローカル合計 ${amount}（Wire 非送信）`,
    rejectReasonPrefix: "却下理由: ",
    localLinesHint: "以下は発行元ローカルの明細です。Wire には載せません。",
    taxTotal: (rate: number, amount: string) => `${rate}% 合計 ${amount}`,
    needApprovePerm: "chat:approve 権限が必要です",
    approving: "承認中…",
    approveClaimed: "承認して claimed",
    reject: "却下",
    rejectClaim: "claim を却下",
    rejectReason: "却下理由",
    rejectPlaceholder: "例: 対象取引と一致しない",
    cancel: "キャンセル",
    doReject: "却下する",
    foot: "ADR 0032 · 金額入力欄なし · 30秒自動更新",
    confirmApprove: (id: string, org: string) =>
      `${id} を承認しますか？\n請求元: ${org}\nWire には receipt_id と digest のみ送信します（金額は送りません）。`,
    claimedSent: (id: string) =>
      `${id} を claimed として Wire 送信しました（amount-free）`,
    needRejectReason: "却下理由を入力してください",
    rejectedMsg: (id: string) => `${id} を却下しました`,
  },
  {
    analyticsTitle: "Analytics dashboard",
    analyticsLead: "KPI scorecards and data quality.",
    loading: "Loading…",
    summary: "Summary",
    kpiGreen: "On track",
    kpiAmber: "Watch",
    kpiRed: "Action needed",
    kpiUnknown: "Unknown",
    dataQuality: "Data quality",
    momPresent: "With MoM",
    attainment: "Target attainment",
    noMetrics: "No metrics yet",
    noMetricsHint: "Set targets to see attainment here.",
    kpiList: "KPI list",
    colRag: "RAG",
    colMetric: "Metric",
    colActual: "Actual",
    colTarget: "Target",
    colMom: "MoM",
    ledgerTitle: "Ledger",
    ledgerLead:
      "Trial balance, balance sheet, journals, subledgers, and monthly post / settle / remittance.",
    asOf: "As of",
    opsMonth: "Ops month",
    reload: "Reload",
    asOfValue: (date: string) => `As of ${date}`,
    monthlyPost: "Monthly posting",
    postDepreciation: "Depreciation + monthly P&L",
    postPayroll: "Payroll payment",
    periodLock: "Period lock",
    noLockHistory: "No lock history",
    colMonth: "Month",
    colStatus: "Status",
    colOperator: "Operator",
    colWhen: "When",
    lock: "Lock",
    unlockReason: "Unlock reason",
    unlock: "Unlock",
    taxBalances: "Tax and remittance balances",
    colAccount: "Account",
    colName: "Name",
    colBalance: "Balance",
    remittanceCalendar: "Remittance calendar",
    noRemittance: "No remittance calendar rows",
    colDeadline: "Deadline",
    colContent: "Item",
    colEstimate: "Estimate",
    remittanceJournal: "Remittance journal",
    monthlyReconcile: (month: string) => `Monthly reconcile ${month}`,
    glActive: "GL active",
    glInactive: "GL inactive",
    matched: "Matched",
    unmatched: "Variance",
    colKind: "Kind",
    colDelta: "Delta",
    balanceSheet: "Balance sheet",
    cashFlow: "Cash flow statement",
    cashFlowMethod: (method: string) => `Method: ${method}`,
    cashFlowOperating: "Operating",
    cashFlowInvesting: "Investing",
    cashFlowFinancing: "Financing",
    cashFlowNetChange: "Net cash change",
    cashFlowBegin: "Cash at beginning",
    cashFlowEnd: "Cash at end",
    cashFlowReconciled: "Reconciled to cash balance",
    cashFlowUnreconciled: "Not reconciled to cash balance",
    downloadCashFlowCsv: "Cash flow CSV",
    assets: "Assets",
    liabilities: "Liabilities",
    equity: "Equity",
    netIncome: "Net income",
    balanced: "Balanced",
    unbalanced: "Unbalanced",
    priorCompare: "Prior period",
    priorAsOf: (date: string) => `Prior period end ${date}`,
    colItem: "Item",
    colCurrent: "Current",
    colPrior: "Prior",
    colDiff: "Delta",
    revenue: "Revenue",
    netProfit: "Net profit",
    ledgerExport: "Ledger export",
    ledgerExportLead: "Download journals, trial balance, and account breakdown as CSV.",
    downloadJournalCsv: "Journal CSV",
    downloadTrialBalanceCsv: "Trial balance CSV",
    downloadAccountBreakdownCsv: "Account breakdown CSV",
    denchoSearch: "Electronic ledger search",
    denchoSearchLead: "Search journal entries by date and description.",
    denchoFrom: "From",
    denchoTo: "To",
    denchoDescription: "Description contains",
    denchoRun: "Search",
    denchoNoHits: "No matches",
    denchoHits: (n: number) => `${n} hits`,
    bankReconcile: "Bank reconcile",
    unmatchedCount: (n: number) => `${n} unmatched`,
    noBankProposals: "No proposals (CLI `jp bank reconcile propose` also works)",
    colBankLine: "Bank line",
    colArAp: "AR/AP",
    colAmount: "Amount",
    colConfidence: "Confidence",
    approveMatch: "Approve match",
    colLine: "Line",
    colDate: "Date",
    colDirection: "Direction",
    trialBalance: "Trial balance",
    debit: "Debit",
    credit: "Credit",
    recentJournals: "Recent journals",
    colId: "ID",
    colMemo: "Memo",
    reverse: "Reverse",
    subsidiary: (code: string, name: string) => `Subledger ${code} ${name}`,
    control: "Control",
    colCounterparty: "Counterparty",
    arReceipt: "AR receipt",
    apPayment: "AP payment",
    unpostedMonths: "Unposted months (budget vs actual)",
    yen: (n: string) => `${n} yen`,
    runsTitle: "Run status",
    runsLead: "Progress of work that is running now.",
    activePlans: "Active plans",
    noActive: "No work in progress",
    noActiveHint: "When new work starts, progress appears here. Ask Steward to create a plan.",
    allPlans: "All plans",
    filterAll: "All",
    filterAttention: "Needs attention",
    filterAgent: "Agent",
    filterWorkKind: "Work kind",
    viewIncomplete: "Incomplete",
    viewCompleted: "Completed",
    viewAll: "All",
    groupByPlan: "Plan",
    groupByAgent: "Agent",
    groupByWorkKind: "Kind",
    groupByDue: "Due date",
    groupLabel: "Group",
    hideEmpty: "Hide empty",
    completedPlans: "Completed plans",
    completeTask: "Mark complete",
    reopenTask: "Mark incomplete",
    completeBusy: "Completing…",
    reopenBusy: "Reopening…",
    confirmComplete: (title: string) => `Mark "${title}" complete?`,
    confirmReopen: (title: string) => `Reopen "${title}"?`,
    dueOverdue: "Overdue",
    dueToday: "Today",
    dueSoon: "Soon",
    dueLater: "Later",
    dueNone: "No due date",
    columnAttention: "Attention",
    columnTodo: "To do",
    columnWaiting: "Waiting",
    columnActive: "In progress",
    columnDone: "Done",
    planProgress: (done: number, total: number) => `${done}/${total}`,
    planAttention: (n: number) => `${n} need attention`,
    workKindUnknown: "Unclassified",
    waitingOn: (title: string) => `Waiting: ${title}`,
    cardDetail: "Details",
    dueDate: "Due",
    assignee: "Assignee",
    blockedOn: "Blocked on",
    workKind: "Kind",
    closeDetail: "Close",
    completed: "Completed",
    summaryOf: (id: string) => `Summary · ${id}`,
    nodes: "Nodes",
    colWave: "Wave",
    blockedDownstream: "Blocked downstream",
    kpiReady: "Ready",
    kpiBlocked: "Blocked",
    retryBusy: "Retrying…",
    retryFailed: "Retry failed",
    cancelBusy: "Stopping…",
    cancelPending: "Stop pending",
    openSteward: "Open in Steward chat",
    statusPending: "Pending",
    statusWaiting: "Waiting",
    statusDispatched: "Dispatched",
    statusRunning: "Running",
    statusCompleted: "Completed",
    statusFailed: "Failed",
    statusBlocked: "Blocked",
    confirmRetry: (id: string) =>
      `${id}: return failed nodes to waiting. Continue?`,
    confirmCancel: (id: string) => `${id}: stop unstarted nodes. Continue?`,
    receiptIssueTitle: "Issue receipt",
    receiptIssueLead:
      "Issue a qualified invoice (or simplified) with a signed QR. The issuer is taken from the tenant corporate number.",
    issuerAuto: "Issuer (automatic)",
    issuerLoading: "Loading issuer…",
    issuer: "Issuer",
    registrationNo: "Registration number",
    corporateNo: "Corporate number",
    issueInput: "Issue input",
    documentType: "Document type",
    qualifiedInvoice: "Qualified invoice",
    qualifiedSimplified: "Qualified simplified invoice",
    transactionDate: "Transaction date",
    recipient: "Addressee",
    recipientPlaceholder: "Counterparty name",
    lines: "Lines",
    addLine: "Add line",
    itemN: (n: number) => `Item ${n}`,
    itemPlaceholder: "Item",
    qtyN: (n: number) => `Quantity ${n}`,
    qtyPlaceholder: "Qty",
    taxN: (n: number) => `Tax rate ${n}`,
    reduced: "Reduced",
    exN: (n: number) => `Amount excl. tax ${n}`,
    exPlaceholder: "Excl. tax",
    includingTax: "Incl. tax",
    delete: "Delete",
    totalIncl: "Total (incl. tax)",
    preview: "Preview",
    issuing: "Working…",
    issue: "Issue",
    previewResult: "Preview result",
    issueResult: "Issue result",
    copyLink: "Copy link",
    downloadPdf: "Download PDF",
    defaultItem: "Item",
    errIssuer:
      "Cannot load issuer (check the corporate number in company.yaml)",
    errRecipient: "Addressee is required for a qualified invoice",
    errLines: "Enter at least one line with an item and amount excluding tax",
    previewUpdated: "Preview updated (not persisted)",
    confirmIssue: (total: string) =>
      `Issue this receipt?\nTotal ${total}\nIt will be stored in the registry.`,
    issued: (id: string) => `Issued ${id}`,
    linkCopied: "Verification link copied",
    receiptTitle: "Receive receipt",
    receiptLead:
      "After the issuer claims, approval returns only receipt_id and digest on Wire. Amounts and lines are never entered or sent.",
    approver: "Approver",
    noAmount: "No amount sent",
    noApprovePerm: "You do not have permission to approve",
    claimStatus: "Claim status",
    pending: "Awaiting approval",
    claimed: "Approved",
    rejected: "Rejected",
    all: "All",
    noClaims: "No matching claims.",
    requestedAt: (when: string) => `Requested ${when}`,
    issuerLocalTotal: (amount: string) =>
      `Issuer-local total ${amount} (not sent on Wire)`,
    rejectReasonPrefix: "Reject reason: ",
    localLinesHint: "Issuer-local lines. Not sent on Wire.",
    taxTotal: (rate: number, amount: string) => `${rate}% total ${amount}`,
    needApprovePerm: "chat:approve permission required",
    approving: "Approving…",
    approveClaimed: "Approve as claimed",
    reject: "Reject",
    rejectClaim: "Reject claim",
    rejectReason: "Reject reason",
    rejectPlaceholder: "e.g. does not match the transaction",
    cancel: "Cancel",
    doReject: "Reject",
    foot: "ADR 0032 · no amount field · auto-refresh every 30s",
    confirmApprove: (id: string, org: string) =>
      `Approve ${id}?\nClaimant: ${org}\nWire sends only receipt_id and digest (no amount).`,
    claimedSent: (id: string) =>
      `Sent ${id} as claimed on Wire (amount-free)`,
    needRejectReason: "Enter a reject reason",
    rejectedMsg: (id: string) => `Rejected ${id}`,
  },
);
