import { defineCopy } from "@ops-shared/define-copy";

export const PEOPLE_COPY = defineCopy(
  {
    yen: "円",
    desk: "経費精算デスク",
    deskLead:
      "個人枠超過は上長承認（expense.claim.manager）。10万超は稟議（expense.claim.ringi · REG-004、共同承認者必須）。自己承認は禁止です。部門枠不足の取込はここには出ません — 先に階層分配で枠を増やしてください。",
    toHierarchyWhenShort: "階層分配へ（部門枠不足時）",
    claimStatus: "精算ステータス",
    tabPending: (n: number) => `承認待ち (${n})`,
    tabReimburse: (n: number) => `弁済待ち (${n})`,
    tabDone: (n: number) => `完了 (${n})`,
    tabRejected: (n: number) => `却下 (${n})`,
    emptyPending: "承認待ちはありません。",
    gateManager: "上長承認待ち",
    gateRep: "代表者承認待ち（REG-004 A）",
    gateLate: "期限超過例外承認待ち",
    gateRingi: "稟議承認待ち（REG-004）",
    gateBoard: "取締役会証跡待ち（REG-004 C）",
    lateSubmit: (days: number) => ` · ${days}日後提出`,
    invoicePrefix: " · T番号:",
    wireSent: " · Wire送信済",
    wireFailed: " · Wire失敗（精算継続）",
    receiptDetail: "領収書詳細",
    coApprover: "共同承認者",
    boardEvent: "取締役会イベント",
    selectPlease: "選択してください",
    confirmApprove: (id: string) => `${id} を承認しますか？`,
    confirmAmount: (amount: string) => `金額: ${amount}`,
    confirmGate: (gate: string) => `gate: ${gate}`,
    confirmCo: (name: string) => `共同承認者: ${name}`,
    confirmBoard: (id: string) => `取締役会: ${id}`,
    noSelfApprove: "自己承認は禁止です。",
    approved: (id: string) => `精算 ${id} を承認しました`,
    approve: "承認",
    reject: "却下",
    reimburseQueue: "立替弁済待ち",
    reimburseLead:
      "月次実績へ計上済み。会社から立替者への弁済（REG-005 第3条）を記録します。",
    pendingReimburse: "弁済待ち",
    transferReady: (ref: string) => ` · 送金準備済 ${ref}`,
    transferNotReady: " · 送金未準備",
    sourceAccount: "出金口座ID",
    payeeId: "支払先ID",
    payeeName: "支払先表示名",
    transferPrepared: (id: string) =>
      `精算 ${id} の送金指示を準備しました（DRY-RUN）`,
    prepareTransfer: "送金を準備",
    paymentRef: "支払参照",
    paymentRefPh: "振込指示ID",
    bankLine: "銀行明細",
    bankLineNone: "未選択（外部証跡を使う）",
    externalEvidence: "外部決済証跡",
    externalEvidencePh: "銀行明細がない場合の決済証跡参照ID",
    reimbursed: (id: string) => `精算 ${id} を弁済済にしました`,
    markReimbursed: "弁済済にする",
    emptyReimburse: "弁済待ちはありません。",
    emptyDone: "完了案件はありません。",
    reimbursedLabel: "弁済済",
    emptyRejected: "却下案件はありません。",
    rejectedLabel: "却下",
    rejectTitle: "精算を却下",
    rejectReason: "却下理由",
    rejectReasonPh: "例: 証憑不備 / 費目不一致",
    cancel: "キャンセル",
    doReject: "却下する",
    rejectedMsg: (id: string) => `精算 ${id} を却下しました`,
    receiptDetailTitle: (id: string) => `領収書詳細 · ${id}`,
    loading: "読み込み中…",
    txnDate: (date: string) => `取引日 ${date}`,
    sigOk: " · 署名OK",
    total: (amount: string) => `合計 ${amount}`,
    noSnapshot: "スナップショットがありません。",
    close: "閉じる",
    companyPersonPool: "全社の個人配布可能費目",
    personAllocatableCats: "個人配布可能な費目",
    toHierarchy: "階層分配へ",
    editEnvelopes: "個人枠の編集",
    personalEnvelope: "個人経費枠",
    personalEnvelopeNote: "建て替え・裁量経費のみ（人件費は別レーン）。",
    department: "部門",
    noDepartments: "部門がありません。",
    noDeptPersonCats:
      "この部門に個人配布可能な費目がありません。先に階層分配で部門費目へ枠を落としてください。",
    openDeptHierarchy: (label: string) => `${label}の階層分配を開く`,
    colPerson: "人員",
    colTotal: "合計",
    updatedEnvelope: "個人枠を更新しました",
    category: "費目",
    amount: "金額",
    personCategoryYen: "個人の費目別分配額（円）",
    cap: "上限",
    overDept: " · 部門枠を超えています",
    applying: "反映中…",
    update: "更新",
    noPermission:
      "この部門の個人配布を変更する権限がありません（部門長または CEO）。",
  },
  {
    yen: "JPY",
    desk: "Expense claims desk",
    deskLead:
      "Over a personal envelope needs manager approval (expense.claim.manager). Over 100,000 yen needs ringi (expense.claim.ringi · REG-004, co-approver required). Self-approval is blocked. Claims blocked by a short department envelope do not appear here — increase the envelope on Allocation first.",
    toHierarchyWhenShort: "Go to Allocation (when a department envelope is short)",
    claimStatus: "Claim status",
    tabPending: (n: number) => `Pending (${n})`,
    tabReimburse: (n: number) => `To reimburse (${n})`,
    tabDone: (n: number) => `Done (${n})`,
    tabRejected: (n: number) => `Rejected (${n})`,
    emptyPending: "No pending approvals.",
    gateManager: "Waiting for manager approval",
    gateRep: "Waiting for representative approval (REG-004 A)",
    gateLate: "Waiting for late-exception approval",
    gateRingi: "Waiting for ringi approval (REG-004)",
    gateBoard: "Waiting for board evidence (REG-004 C)",
    lateSubmit: (days: number) => ` · submitted ${days} days later`,
    invoicePrefix: " · T-number:",
    wireSent: " · Wire sent",
    wireFailed: " · Wire failed (claim continues)",
    receiptDetail: "Receipt detail",
    coApprover: "Co-approver",
    boardEvent: "Board event",
    selectPlease: "Select",
    confirmApprove: (id: string) => `Approve ${id}?`,
    confirmAmount: (amount: string) => `Amount: ${amount}`,
    confirmGate: (gate: string) => `gate: ${gate}`,
    confirmCo: (name: string) => `Co-approver: ${name}`,
    confirmBoard: (id: string) => `Board: ${id}`,
    noSelfApprove: "Self-approval is blocked.",
    approved: (id: string) => `Approved claim ${id}`,
    approve: "Approve",
    reject: "Reject",
    reimburseQueue: "Reimbursement pending",
    reimburseLead:
      "Posted to monthly actuals. Record company reimbursement to the person (REG-005 Article 3).",
    pendingReimburse: "To reimburse",
    transferReady: (ref: string) => ` · transfer prepared ${ref}`,
    transferNotReady: " · transfer not prepared",
    sourceAccount: "Source account ID",
    payeeId: "Payee ID",
    payeeName: "Payee display name",
    transferPrepared: (id: string) =>
      `Prepared a transfer instruction for claim ${id} (DRY-RUN)`,
    prepareTransfer: "Prepare transfer",
    paymentRef: "Payment reference",
    paymentRefPh: "Transfer instruction ID",
    bankLine: "Bank statement",
    bankLineNone: "None (use external evidence)",
    externalEvidence: "External settlement evidence",
    externalEvidencePh: "Settlement evidence ID when there is no bank line",
    reimbursed: (id: string) => `Marked claim ${id} as reimbursed`,
    markReimbursed: "Mark reimbursed",
    emptyReimburse: "Nothing waiting for reimbursement.",
    emptyDone: "No completed claims.",
    reimbursedLabel: "Reimbursed",
    emptyRejected: "No rejected claims.",
    rejectedLabel: "Rejected",
    rejectTitle: "Reject claim",
    rejectReason: "Reason",
    rejectReasonPh: "Example: missing evidence / category mismatch",
    cancel: "Cancel",
    doReject: "Reject",
    rejectedMsg: (id: string) => `Rejected claim ${id}`,
    receiptDetailTitle: (id: string) => `Receipt detail · ${id}`,
    loading: "Loading…",
    txnDate: (date: string) => `Transaction date ${date}`,
    sigOk: " · signature OK",
    total: (amount: string) => `Total ${amount}`,
    noSnapshot: "No snapshot.",
    close: "Close",
    companyPersonPool: "Company person-allocatable categories",
    personAllocatableCats: "Person-allocatable categories",
    toHierarchy: "Go to Allocation",
    editEnvelopes: "Edit personal envelopes",
    personalEnvelope: "Personal expense envelope",
    personalEnvelopeNote:
      "Reimbursable and discretionary expenses only (payroll is a separate lane).",
    department: "Department",
    noDepartments: "No departments.",
    noDeptPersonCats:
      "This department has no person-allocatable categories. Drop envelope into department categories on Allocation first.",
    openDeptHierarchy: (label: string) => `Open Allocation for ${label}`,
    colPerson: "Person",
    colTotal: "Total",
    updatedEnvelope: "Updated the personal envelope",
    category: "Category",
    amount: "Amount",
    personCategoryYen: "Person category allocation (JPY)",
    cap: "Cap",
    overDept: " · over the department envelope",
    applying: "Applying…",
    update: "Update",
    noPermission:
      "You do not have permission to change person allocation in this department (department head or CEO).",
  },
);
