import { defineCopy } from "@ops-shared/define-copy";

export const STEWARD_COPY = defineCopy(
  {
    yojitsuMenu: "予実メニュー",
    ledgerMenu: "帳簿メニュー",
    transactionsMenu: "取引メニュー",
    agentsMenu: "エージェントメニュー",
    wallet: "個人予実",
    analytics: "分析",
    ledger: "帳簿",
    tax: "税務",
    onboarding: "セットアップ",
    customers: "顧客管理",
    customersMenu: "顧客管理メニュー",
    customersOutbound: "アウトバウンド",
    customersInbound: "インバウンド",
    customersPipeline: "パイプライン",
    customersAccounts: "顧客・担当者",
    customersAfterSales: "アフターセールス",
    customersChurn: "解約・休眠",
    customersLead: "見込み客から既存顧客までの一覧と更新。送信と受注引渡しは承認が必要です。",
    customersLockedLead: "セールスまたはカスタマーサクセスモジュールが Off のため、顧客管理は使えません。",
    customersSalesGrace: "セールス Agent は有効ですが、モジュールが未取込です。",
    customersModuleLocked: "この面を表示するモジュールが Off です。",
    customersAskSteward: "スチュワードに聞く",
    customersCampaigns: "アウトバウンド施策",
    customersActiveCampaigns: (active: number, total: number) =>
      `実行中 ${active} / 全 ${total} 件`,
    customersCoverage: (pct: number) => `接触率 ${pct}%`,
    customersNoAlerts: "いま要対応のアラートはありません。",
    customersOpenDeals: "進行中の商談",
    customersPipelineDeals: "商談一覧",
    customersAccountsList: "顧客一覧",
    customersPromoteInquiry: "商談化",
    customersSetStage: "ステージ更新",
    customersSaveNextAction: "次アクション保存",
    customersNextActionLabel: "次アクション",
    customersNextActionDueLabel: "期限",
    customersLostReasonLabel: "失注理由",
    customersEditInPipeline: "パイプラインで編集",
    customersQualifiedPromote: "商談化候補（qualified）",
    customersAmbiguousMail: (n: number) =>
      `メール紐付けが曖昧な triage が ${n} 件あります。CLI: orgos sales mail-link-resolve`,
    customersMailLinkCliHint: "曖昧なメール紐付けは CLI で解決してください。",
    customersMergeCliHint: "重複アカウントのマージは CLI: orgos sales account merge --from … --into …",
    customersPromoteDone: "商談を作成しました。パイプラインで確認できます。",
    customersActionError: "更新に失敗しました。",
    customersPipelineSummary: (open: number, weightedMan: number) =>
      `オープン ${open} 件 · 加重 ${weightedMan} 万円`,
    customersInquiryQueue: "問合せキュー",
    customersInquirySummary: (open: number, total: number) =>
      `未処理 ${open} / 全 ${total} 件`,
    customersHealth: "顧客ヘルス",
    customersHealthSummary: (
      total: number,
      healthy: number,
      atRisk: number,
      critical: number,
    ) => `全 ${total} 社 · healthy ${healthy} · at_risk ${atRisk} · critical ${critical}`,
    customersRenewals: "更新間近",
    customersChurnSummary: "解約・休眠",
    customersChurnCounts: (
      atRisk: number,
      critical: number,
      churned: number,
      dormant: number,
    ) =>
      `at_risk ${atRisk} · critical ${critical} · churned ${churned} · 休眠 ${dormant}`,
    customersChurnEvents: "解約イベント（直近）",
    account: "アカウント",
    runs: "実行状況",
    admin: "予算管理",
    receiptIssue: "領収書発行",
    receipt: "領収書の受け取り",
    secretary: "秘書",
    steward: "スチュワード",
    agentList: "エージェント一覧",
    agentListEmpty: "有効なエージェントはまだありません。",
    agentListLead:
      "スチュワードと秘書は既定窓口のため Off にできません。部門エージェントは切り替えられます。",
    agentDeskSection: "既定窓口",
    agentDeptSection: "部門エージェント",
    agentChainTitle: "依頼・報告の系統",
    agentChainLead:
      "社内への依頼はスチュワードを経由します。会社データの書き換えは、オーナーがスチュワードに直接依頼した場合のみ行われます。",
    agentDeskBadge: "既定窓口",
    agentDeskFixed: "常時 On · Off にできません",
    agentLaneSteward: "オーナー直 → 全社オーケストレーション",
    agentLaneSecretary: "オーナー直 → 社内照会はスチュワード経由",
    agentLaneViaSteward: "依頼はスチュワード経由",
    reportsToLine: (label: string) => `報告: ${label}`,
    agentSection: "エージェント",
    agentSectionLead: "使う / 使わないを切り替えます。必須の担当は Off にできません。",
    agentSearchPlaceholder: "エージェントを検索",
    moduleList: "モジュール一覧",
    moduleListEmpty: "有効なモジュールはまだありません。",
    moduleListLead: "いま有効なモジュールです。Off は承認後に無効になります。",
    moduleInstalledSection: "取り込み済みモジュール",
    moduleInstalledLead: "取り込んだあとで On / Off します。On にするには承認が必要です。",
    moduleSearchPlaceholder: "モジュールを検索",
    agentAdd: "エージェント追加",
    agentAddLead: "まだ使っていないエージェントを検索して追加します。",
    agentAddEmpty: "追加できるエージェントはありません。",
    agentAdded: "追加しました。",
    agentProposedAdd: "追加を提案しました。CEO は承認タブで確認してください。",
    agentPendingAdd: "追加の承認待ち（承認タブ）",
    moduleAddTab: "モジュール追加",
    moduleAddLead: "未導入のモジュールを取り込みます。取り込んだ直後は Off です。",
    moduleAdd: "追加",
    moduleAdding: "追加中…",
    moduleEmptyInstalled: "取り込み済みのモジュールはまだありません。",
    moduleEmptyCatalog: "追加できるモジュールはありません。",
    moduleNoMatch: "該当するモジュールがありません。",
    agentNoMatch: "該当するエージェントがありません。",
    toggleOn: "On",
    toggleOff: "Off",
    toggleAgent: (name: string) => `${name} を使う`,
    toggleModule: (name: string) => `${name} を On`,
    agentLockedRequired: "コア担当のため Off にできません。",
    agentLockedOwnerDesk: "オーナーの既定窓口のため Off にできません。",
    agentLockedModule: "モジュールが On のあいだは Off にできません。先にモジュールを Off にしてください。",
    modulePendingOn: "有効化の承認待ち（承認タブ）",
    modulePendingOff: "無効化の承認待ち（承認タブ）",
    moduleProposedOn: "有効化を提案しました。CEO は承認タブで確認してください。",
    moduleProposedOff: "無効化を提案しました。CEO は承認タブで確認してください。",
    moduleProposedImport: "追加を提案しました。CEO は承認タブで確認してください。",
    modulePendingImport: "追加の承認待ち（承認タブ）",
    readonlyToggles: "この操作の権限がありません。",
    chatLead: "聞きたいことを書いて送ると、ここに返答が残ります。",
    message: "メッセージ",
    sendPlaceholder: "⌘/Ctrl+Enter で送信",
    send: "送信",
    notify: "完了通知を許可",
    conversation: (title: string) => `${title}の会話`,
    loading: "読み込み中…",
    emptyChat: "まだ会話がありません。",
    emptyChatHint: "上の入力欄から送信すると、ここに履歴が残ります。",
    generating: "応答を生成中…",
    generatingCount: (n: number) => `応答を生成中…（${n} 件）`,
    feedbackLabel: "回答の評価",
    feedbackGood: "良い",
    feedbackBad: "悪い",
    feedbackThanks: "評価を保存しました",
    faqServedBadge: "FAQ から即答（LLM なし）",
    faqSection: "FAQ 索引",
    faqBuild: "FAQ 索引を更新",
    faqBuilding: "更新中…",
    faqBuilt: (n: number) => `FAQ 索引を更新しました（${n} 件）`,
    faqBuildLead: "Good 評価の Q&A を索引化し、同じ質問には LLM を使わず答えます。",
    llmRouteLabel: "LLM",
    llmRouteAuto: "自動（ローカル優先）",
    llmRouteLocalAny: "ローカル（任意）",
    llmRouteCloudAny: "クラウド（任意）",
    llmRouteGroupLocal: "ローカル",
    llmRouteGroupCloud: "クラウド",
    llmRouteStatusLoading: "ローカル LLM を確認しています…",
    llmRouteStatusUnavailable: "ワーカー状態を取得できません",
    llmRouteStatusConnected: (name: string) => `${name} に接続済み`,
    llmRouteStatusDisconnected: (name: string) => `${name} に未接続`,
    llmRouteStatusNoLocal: "ローカルワーカーがありません",
    workersLinkBefore: "LLM ワーカーは",
    workersLink: "ワーカー設定",
    cloudLinkBefore: "有料のクラウドサービスの切り替えは",
    cloudLink: "クラウド接続",
    historyLinkBefore: "履歴の保持件数は",
    historyLink: "履歴の件数",
    chatSettingsTitle: "チャット履歴の設定",
    chatSettingsLead:
      "会話は端末内に保存されます。保持する往復数より古いものは自動で削除されます。",
    mailSection: "メール",
    mailSettingsPointer: "送信元と Gmail 連携は会社の設定にあります。",
    companySettingsLink: "会社の設定",
    mailConnected: (email: string) => `Gmail 接続済み（${email}）`,
    mailNotConnected: "Gmail 未接続",
    mailExpired: "トークンの期限が切れています。再度連携してください。",
    mailFromName: "送信元の表示名",
    mailFromEmail: "送信元アドレス",
    mailProvider: "送信方法",
    mailSmtpHost: "SMTP ホスト",
    mailSmtpPort: "SMTP ポート",
    mailSecretsNote:
      "OAuth トークンはこの画面では扱いません。SMTP / IMAP のパスワードは下の欄からサーバ側の秘密ストアに保存します。",
    hubTitle: "Witness Hub 運用",
    hubBind: "bind",
    hubBindPublic: "公開",
    hubBindLoopback: "ループバック",
    hubBindAllowed: "公開可",
    hubBindBlocked: "公開不可",
    hubTlsPresent: "配置済み",
    hubTlsMissing: "未配置",
    hubTlsExpires: "期限",
    hubTlsExpired: "期限切れ",
    hubTlsPlacement:
      "証明書は deploy/witness-hub/tls/server.pem と server.key に配置します。秘密鍵はブラウザから送信しません（画面は検証のみ）。",
    hubMetricsUp: "到達",
    hubMetricsDown: "未到達",
    hubReadyForRelay: "公開リレー可否",
    hubYes: "可",
    hubNo: "不可",
    platformTitle: "運営コンソール",
    platformLead:
      "プラットフォーム運営専用。テナントの画面には出ません（ORGOS_PLATFORM_OPERATORS で許可）。",
    platformFlags: "出荷フラグ",
    platformCommunityEnv: "Community 側の env",
    platformEnvShipped: "出荷済み",
    platformEnvNotShipped: "未出荷",
    platformEnvHowTo:
      "Community に COMMUNITY_TENANT_MAIL_CONNECT_SHIPPED=1 を設定して再デプロイしてください。",
    esignTitle: "国家 eID 署名",
    esignLead:
      "カード・リーダー・PIN は署名者の端末に留まります。コンソールはコンテナと SiVa の判定だけを扱います。",
    esignServices: "サービス状態",
    esignSidecar: "digidoc4j サイドカー",
    esignSidecarUp: "応答あり",
    esignUnset: "未設定",
    esignLiveOk: "live 検証が可能",
    esignLiveMissing: "live 検証には SiVa の設定が必要",
    esignNewCase: "案件を作成",
    esignCaseTitle: "件名",
    esignCaseTitlePlaceholder: "例: 秘密保持契約",
    esignPdf: "PDF",
    esignCreate: "作成",
    esignCreated: "を作成しました",
    esignCases: "案件",
    esignNoCases: "案件はありません。",
    esignStatus: "状態",
    esignPrepare: "骨組み生成",
    esignPrepared: "の unsigned.asice を生成しました",
    esignAttach: "署名済みを添付",
    esignAttached: "に署名済みコンテナを添付しました",
    esignVerify: "SiVa 検証",
    esignVerified: "TOTAL-PASSED（completed）",
    esignNotVerified: "国家検証は未完了",
    esignDigestMismatch: "添付コンテナに元 PDF の digest が見つかりません",
    esignSignOnDevice:
      "DigiDoc4 とカードで署名し、生成された .asice を選んでから添付してください。",
    esignSignedContainer: "署名済み .asice",
    esignPickPdf: "PDF を選んでください。",
    esignPickAsice: "署名済み .asice を選んでください。",
    esignTitleRequired: "件名を入力してください。",
    mailSecretsTitle: "SMTP / IMAP の秘密",
    mailSecretsStored:
      "保存先は data/secrets/mail-secrets.env（git 管理外・0600）。保存後は画面に表示されず、マスク済みの手がかりだけが返ります。",
    mailSecretsSave: "秘密を保存",
    mailSecretSet: "設定済み",
    mailSecretUnset: "未設定",
    mailSmtpUser: "SMTP ユーザー",
    mailSmtpPassword: "SMTP パスワード",
    mailImapHost: "IMAP ホスト",
    mailImapUser: "IMAP ユーザー",
    mailImapPassword: "IMAP パスワード",
    mailConnect: "Gmail と連携する",
    mailDisconnect: "連携を解除",
    mailConnectOpen: "Community で連携を完了する",
    maxTurns: "保持する往復数",
    turns: (n: number) => `${n} 往復`,
    save: "保存",
    saved: "保存しました",
    savedPruned: (n: number) => `保存しました（${n} 件の履歴を上限に合わせて整理）`,
    backSteward: "スチュワードに戻る",
    backSecretary: "秘書に戻る",
    approvalsLabel: "CEO 承認受信箱",
    approvalsTitle: "承認",
    approvalsLead: "CEO の確認が必要な項目。",
    approvalsEmpty: "いま承認待ちはありません。",
    previewLoading: "差分を読み込み中…",
    previewToggle: "本文",
    approving: "処理中…",
    approveApply: "承認して適用",
    ceoQuestionsTitle: "CEO への確認",
    ceoQuestionAnswer: "回答する",
    correspondencePendingTitle: "対外メール・送信待ち",
    correspondencePendingEmpty: "送信待ちの下書きはありません。",
    correspondenceDryRun: "送信ドライラン",
    correspondenceSend: "送信する",
    brokerTransferTitle: "振込指示",
    brokerTransferLead: "口座番号はマスク表示。送金はネットバンキングで実行します。",
    brokerFrom: "出金口座",
    brokerAmount: "金額（円）",
    brokerPayee: "振込先名",
    brokerReference: "摘要",
    brokerDryRun: "ドライラン",
    brokerWrite: "指示書を保存",
    towerCardTitle: "司令塔の割当",
    towerJudgmentOnly: "判断・承認が必要です。",
    towerAssigned: "割当済み",
    towerAssignee: "担当（従業員）",
    towerDueDate: "期限",
    towerConfirm: "割当を確定",
    companyEventsTitle: "会社イベント（未クローズ）",
    companyEventsEmpty: "当月の未クローズイベントはありません。",
    companyEventKind: "種別",
    companyEventTitleField: "タイトル",
    companyEventCreate: "起票",
    companyEventClose: "クローズ",
    companyEventArchive: "アーカイブ",
    companyEventVoid: "無効化",
    companyEventVoidReason: "無効化の理由（必須）",
    companyEventChainVerify: "チェーン検証",
    companyEventChainOk: "チェーン検証 OK",
    companyEventChainNg: "チェーン検証に失敗しました",
    companyEventIncludeClosed: "クローズ・無効も表示",
    executiveNotifyLabel: "要対応のデスクトップ通知",
    executiveNotifyHint: "要対応があるとき通知する",
    reject: "却下",
    settlementPasskeyRequired: "決済 PassKey（iPhone）の登録が必要です。",
    settlementPasskeySettingsLink: "設定で iPhone を登録",
    cloudTitle: "クラウド LLM の接続",
    cloudLead:
      "ローカル LLM より速い応答が必要なとき、OpenAI か Anthropic の API キーを設定します。利用料は各社の課金です。",
    cloudStep1: "1. API キーを取得",
    cloudStep2: "2. Console 起動時の環境変数",
    cloudExampleOpenai: "例（OpenAI）:",
    cloudExampleClaude: "例（Claude）:",
    cloudRestart: "設定後、Operator Console を再起動してください。",
    cloudNotes: "注意",
    cloudNotesBody:
      "クラウドに送る文脈はデータ分類（L0–L3）と Operator Policy に従ってください。給与・原価・個情などは載せないでください。",
    adminTitle: "予算管理",
    adminLead: "部門・配分・見通しを決定論データから操作します。",
    executiveTitle: "経営ダッシュボード",
    executiveLead: "要対応・目標ギャップ・依頼進捗。",
    executiveAttention: "要対応",
    executiveRunway: "ランウェイ",
    executiveCash: "現預金",
    executiveKindCustomer: "顧客",
    executiveKindMail: "メール",
    executiveKindScheduling: "日程",
    executiveKindCeoQuestion: "CEO 確認",
    executiveKindApproval: "承認",
    executiveKindWire: "組織間通知",
    executiveAttentionEmpty: "いま要対応の項目はありません。",
    executiveGaps: "目標とギャップ",
    executiveGapsEmpty: "KPI 定義がありません。",
    executiveTargetMissing: "未設定",
    executiveWork: "依頼と進捗",
    executiveWorkEmployee: "部下",
    executiveWorkGuest: "社外",
    executiveWorkAi: "AI",
    executiveWorkUnassigned: "未割当",
    executiveWorkEmpty: "未完了の依頼はありません。",
    executiveAgentSummaries: "Agent 要約",
    executiveVariance: "売上予実",
    executiveRefresh: "更新",
    executiveAskSteward: "スチュワードに聞く",
    executiveOpenApprovals: "承認へ",
    executiveOpenRuns: "実行状況へ",
    executiveRagGreen: "順調",
    executiveRagAmber: "注意",
    executiveRagRed: "要対応",
    executiveRagUnknown: "不明",
    executiveGapActual: "実績",
    executiveGapTarget: "目標",
    workersTitle: "LLM ワーカー",
    workersLead: "各チャットで Auto / ローカル / クラウドを選べます。キーは環境変数名のみ保存します。",
    workersRunning: (inflight: number, queued: number) => `実行中 ${inflight} · 待機 ${queued}`,
    workersQueue: "キュー",
    workersQueueLimit: "待ち行列上限",
    workersDelete: "削除",
    workersManual: "+ 手動",
    workersNew: "新規ワーカー",
    budgetView: "予算ビュー",
    budgetPeople: "個人配布",
    budgetOverview: "階層分配",
    budgetPlans: "事業計画",
    budgetOutlook: "見通し",
    budgetPayroll: "人件費",
    budgetSources: "正本",
    budgetHistory: "履歴",
    close: "閉じる",
    onboardingReady: "利用準備が完了しています",
    onboardingNotReady: "利用準備が完了していません",
    onboardingLead:
      "帳簿を使うには会社情報と初回仕訳が必要です。ログインには Passkey が必須です。",
    walletLanes: "表示レーン",
    envelope: "経費枠",
    payrollMatch: "一致",
    payrollUnbooked: "未計上",
    payrollCheck: "要確認",
    personSwitch: "個人の切替",
    reloadFailed: "更新失敗 — 表示は前回のままです。",
    retry: "再試行",
    envelopeSummary: "経費枠要約",
    envelopeAndActual: "経費枠と実績",
    envelopeActual: "経費実績",
    remaining: "残額",
    noEnvelope: "この人への個人経費枠はまだありません。",
    receiptIngest: "領収書取込",
    walletLoading: "個人予実を読み込み中…",
    actualThrough: (month: string) => `実績〜${month}`,
    noActuals: "実績なし",
    fetched: (label: string) => `取得 ${label}`,
    refreshing: " · 更新中",
    refresh: "更新",
    refreshingShort: "更新中",
    refetch: "再取得",
    justNow: "たった今",
    secondsAgo: (n: number) => `${n}秒前`,
    minutesAgo: (n: number) => `${n}分前`,
    hoursAgo: (n: number) => `${n}時間前`,
    notFetched: "未取得",
    checklist: "確認事項",
    sevCritical: "要対応",
    sevWarn: "確認",
    sevInfo: "質問",
    revisionTitle: "楽観的同時実行トークン",
    envelopeOver: "経費枠超過",
    ingestTitle: "領収書を取り込む",
    ingestLead:
      "発行組織の署名付き QR リンクまたは JSON を貼り付け、費目を選んで精算します。",
    splitAlloc: "複数科目に分割配賦する",
    splitAllocLegend: "分割配賦（合計＝領収書総額",
    splitAllocClose: "）",
    splitFromQr: " · QR明細から自動入力",
    categoryN: (n: number) => `費目 ${n}`,
    amountYen: "金額（円）",
    removeRow: "行を削除",
    addRow: "行を追加",
    category: "費目",
    qrPayload: "QR / 署名付きペイロード",
    qrPlaceholder: "https://receipt.oorgos.org/r#v2z.… または JSON",
    ingesting: "取込中…",
    ingest: "取り込む",
    claims: "精算案件",
    claimPendingReimburse: "弁済待ち",
    claimReimbursed: "弁済済",
    claimPosted: "計上済",
    claimPendingApproval: "承認待ち",
    claimApproved: "承認済",
    claimRejected: "却下",
    wireSent: "Wire送信済",
    wireFailed: "Wire失敗（精算継続）",
    wireSkipped: "Wireスキップ",
    wireReady: "Wire対象",
    wireNone: "Wireなし",
    invoiceFormatOnly: "T番号:format_only",
    invoiceVerified: "T番号:verified",
    lateSubmit: (days: string) => `${days}日後提出`,
    progressIngest: "進捗: 取込",
    progressPendingApproval: " → 承認待ち",
    progressRejected: " → 却下",
    progressApproved: " → 承認",
    progressPostedPending: " → 計上 → 弁済待ち",
    progressReimbursed: " → 計上 → 弁済済",
    reasonPrefix: " · 理由: ",
    categories: "費目",
    categoriesTable: "費目の経費枠・実績・残額",
    colCategory: "費目",
    colEnvelope: "経費枠",
    colActual: "実績",
    colRemaining: "残額",
    accountMeeting: "5730 会議費",
    accountEntertainment: "5710 交際費",
    accountTravel: "5720 旅費交通費",
    syncUpdatedElsewhere: "他画面で予算が更新されました（再取得済み）",
    syncFromAdmin: "管理画面の変更を反映しました",
    syncBudgetUpdated: "予算データが更新されました",
    ingestNeedDept: "部門と領収書ペイロードが必要です",
    ingestSplitNeedTwo: "分割配賦は2行以上、各行は正の金額が必要です",
    ingestSplitMismatch: (total: number, expected: number) =>
      `分割配賦の合計 ${total} が領収書総額 ${expected} と一致しません`,
    ingestDone: "取込完了",
    ingestConflict:
      "他の操作者が先に精算を更新しました。最新を再取得しました。内容を確認して再度取り込んでください。",
    ingestBlockedDept:
      " — 管理画面の「階層分配へ」から部門枠を先に増やしてください",
    gateAllowImmediate: "枠内・即時精算可",
    gateNeedsManager: "上長承認が必要",
    gateNeedsRep: "代表者承認が必要",
    gateNeedsLate: "期限超過例外承認が必要",
    gateNeedsRingi: "稟議承認が必要（REG-004）",
    gateNeedsBoard: "取締役会証跡が必要（REG-004 C）",
    gateBlockedDept: "部門枠不足（先に階層分配へ）",
    gateBlockedCompany: "全社枠不足",
    gateShortAllow: "枠内",
    gateShortManager: "上長待ち",
    gateShortRep: "代表者待ち",
    gateShortLate: "期限例外待ち",
    gateShortRingi: "稟議待ち",
    gateShortBoard: "取締役会待ち",
    gateShortDept: "部門枠不足",
    gateShortCompany: "全社枠不足",
    claimApprovalsTitle: "経費精算",
    claimApprovalsEmpty: "承認待ちの精算はありません。",
    claimWho: "申請者",
    claimAmount: "金額",
    claimRemaining: "残枠",
    claimDueOn: "返す日",
    claimApproveWithDue: "承認して返す日を決める",
    claimSendBack: "差し戻す",
    claimApproving: "処理中…",
    claimCoApprover: "もう一人の承認者",
    claimBoardEvent: "取締役会の記録",
    claimNeedCoApprover: "この金額はもう一人の承認者が必要です。",
    claimNeedBoardEvent: "この金額は取締役会の記録が必要です。",
    claimSelectPlease: "選んでください",
    claimDeskTitle: "経費の申請",
    claimDeskLead: "領収書のQRを読み取って出すだけです。返る日はこの画面に出ます。",
    claimDeskRemaining: "使える残り",
    claimDeskCategory: "何に使ったか",
    claimDeskScan: "QRを読み取る",
    claimDeskStopScan: "読み取りをやめる",
    claimDeskNoCamera:
      "この端末ではカメラで読み取れません。QRの文字を貼ってください。",
    claimDeskPaste: "QRの文字を貼る",
    claimDeskSubmit: "出す",
    claimDeskSubmitting: "送信中…",
    claimDeskDone: "出しました。",
    claimDeskMine: "自分の申請",
    claimDeskEmpty: "まだ申請はありません。",
    claimDeskWaiting: "待ち",
    claimDeskPassed: "通った",
    claimDeskSentBack: "差し戻し",
    claimDeskBackOn: (date: string) => `返る日 ${date}`,
    claimDeskBackUnset: "返る日は承認後に決まります",
    claimDeskNoEnvelope: "あなたの枠がまだありません。上長に枠の設定を頼んでください。",
    claimDeskScanning: "QRにカメラを向けてください",
    claimDeskCameraDenied: "カメラを使えませんでした。QRの文字を貼ってください。",
    claimDeskSignOut: "ログアウト",
    payrollCompanyTitle: "人件費（全社）",
    payrollEmpty: "人件費データがありません。",
    payrollNonePerson: (name: string) => `${name}に人件費の割当はありません。`,
    payrollNoneGeneric: "人件費の割当はありません。",
    payrollKindOfficer: "役員報酬",
    payrollKindEmployee: "給与",
    payrollKindNone: "対象外",
    payrollReconcile: "突合",
    payrollExpected: "期待",
    payrollBooked: "計上",
    payrollVariance: "差額",
    payrollOfficerMonthly: "役員（月）",
    payrollEmployeeMonthly: "従業員（月）",
    payrollOfficers: "役員",
    payrollMonthly: "月次",
    payrollMonthlyAmount: "月額",
    payrollExpectedCum: "期待累計",
    payrollBookedCum: "計上累計",
    yen: "円",
    workersCloudOverflow: "クラウド昇格",
    workersWaitThreshold: "待ちしきい値 (ms)",
    workersTable: "ワーカー",
    workersColStatus: "状態",
    workersColName: "名前",
    workersColKind: "種別",
    workersColModel: "モデル",
    workersColConcurrent: "同時",
    workersColKeyEnv: "キー env",
    workersColEnabled: "有効",
    workersProbe: "疎通",
    workersNewLabel: "新規ワーカー",
    commandFallback: "コマンド",
    commandFailed: "実行に失敗しました",
    commandHumanGate:
      "人間ゲートです。Wire / 振込 / 承認 UI から実行してください。",
    commandRun: "実行する",
    commandRerun: "再実行",
    budgetValidating: "予算正本を検証しています…",
    budgetLoadFailed: "予算データの読込に失敗しました",
    budgetLoadHint: "ネットワークや認証を確認し、再試行してください。",
    companyUnset: "全社予算が未設定",
    companyUnsetTip: "年度と全社枠を登録すると開始できます。",
    expenseBudget: "経費予算",
    revenueBudget: "売上予算",
    unset: "未設定",
    companyBudgetYen: "全社予算（円）",
    companyBudgetSet: "全社予算を設定しました",
    startFromPlan: "事業計画基準で開始",
    fiscalYear: "会計年度",
    planApprovedFix: "承認済み・FIX",
    planApproved: "承認済み",
    planPending: "承認待ち",
    planDraft: "草案",
    monthShort: (n: number) => `${n}月`,
    subtotal: "小計",
    officerPayrollSubtotal: "役員報酬・人件費 小計",
    corporateSubtotal: "全社統括 小計",
    businessUnit: "事業ユニット",
    corporateExpense: "全社共通経費",
    colAccount: "科目",
    colAmount: "金額",
    total: "合計",
    none: "なし",
    revenueBreakdown: "売上内訳",
    expenseBreakdown: "経費内訳",
    corporateCommon: "全社共通",
    sourcesTip: "画面から直接編集しない。",
    recordCount: (n: number) => `${n}件`,
    noHistory: "まだ履歴はありません。",
    conflictOther:
      "他の操作者が先に更新しました。最新を再取得しました。内容を確認して再度操作してください。",
    retriedLatest: (message: string) => `${message}（最新を取得して再試行しました）`,
    syncFromOther: "他画面の予算更新を反映しました",
    syncReloaded: "最新の予算を再取得しました",
    envelopeProposal: (suggested: string, current: string | null) =>
      current
        ? `枠提案 ${suggested}（現行 ${current}）`
        : `枠提案 ${suggested}`,
    midOutlook: "期中見通し",
    outlookOpex: "見通し（経費）",
    outlookProfitTip: (amount: string) =>
      `利益の目安 ${amount}（売上 − 経費 − 減価償却）`,
    plan: "計画",
    outlookActualThrough: (label: string) => `実績（〜${label}）`,
    vsPlan: "計画との差",
    vsPlanTip:
      "見通しの経費 − 承認済み計画の経費。プラスは計画超過の見込みです。",
    outlookOverEnvelope:
      "見通しの経費が執行枠を超えています。枠の変更は「階層分配」タブ。",
    deptOutlookGap: (delta: string) =>
      `部門合計と全社見通しにずれ（差 ${delta}）。`,
    monthlyOpex: "月次（経費）",
    showMoreMonths: "売上・投資・減価も表示",
    colMonth: "月",
    colRole: "区分",
    roleTip:
      "「確定実績」はすでに確定した月、「見込み」は残月の予測です。",
    opex: "経費",
    revenue: "売上",
    capex: "投資",
    depreciation: "減価",
    actual: "実績",
    forecast: "見込み",
    deptOutlook: "部門の見通し（経費）",
    department: "部門",
    deptOutlookOpex: "経費見通し",
    editForecast: "見込み編集",
    outlookInited: "見通しを初期化しました",
    init: "初期化",
    outlookSynced: "残月を予実から同期しました（公開し直してください）",
    syncFromYojitsu: "予実から同期",
    proposalComputed: "枠提案を計算しました",
    proposal: "枠提案",
    proposalNote: (suggested: string, current: string, delta: string) =>
      `枠提案 ${suggested}（現行 ${current} · 差 ${delta}）。自動では変わりません。変更は「階層分配」タブ。`,
    needAsOf: "基準月を入力してください",
    asOfUpdated: (month: string) => `基準月を ${month} に更新しました`,
    asOfMonth: "基準月",
    asOfTip: "ここまでが確定実績です。これより後の月は見込みとして扱います。",
    needTargetMonth: "対象月を入力してください",
    monthSaved: (month: string) => `${month} の見通しを保存しました`,
    targetMonth: "対象月",
    targetMonthTip: "見込みを入れる月です。一覧から1つ選んでください。",
    needApprover: "承認者を選んでください",
    outlookPublished: "見通しを公開しました",
    publisher: "承認者",
    publisherTip:
      "編集した人以外の、組織上の人（CEO・部門長）を選びます。表示は組織図の氏名です。秘書・エージェントは選べません。",
    selectPlease: "選択してください",
    publish: "公開",
    noOtherApprover:
      "承認できる部門長が他にいません（自己承認不可）。operators に承認ロールの部門長を登録してください。",
    businessPlan: "事業計画",
    businessPlanTip: "売上・経費の計画参照。予算の分配は「分配」タブ。",
    businessPlanAmount: (amount: string) => `事業計画 ${amount}`,
    mismatch: " · 不一致",
    operatingProfit: "営業利益",
    operatingProfitTip:
      "損益計算書の営業利益計画（business-plan）。法人税等控除前。税引前当期純利益そのものではない。支払利息は本テナントでは経費（SGA）に含めている。",
    capexEquipment: "投資（設備）",
    sgaPlan: (amount: string) => `SGA ${amount}`,
    openaiCompat: "OpenAI互換",
    localKeyOptional: "ローカルはキー任意",
    envReady: "env 設定済",
    keyInEnv: "キーは .env に設定",
    presets: "定型追加",
    presetExists: "同種が既にあります（追加可）",
    monthSelect: "月を選択",
  },
  {
    yojitsuMenu: "Budget menu",
    ledgerMenu: "Ledger menu",
    transactionsMenu: "Transactions menu",
    agentsMenu: "Agent menu",
    wallet: "Personal budget",
    analytics: "Analytics",
    ledger: "Ledger",
    tax: "Tax",
    onboarding: "Setup",
    customers: "Customers",
    customersMenu: "Customer management menu",
    customersOutbound: "Outbound",
    customersInbound: "Inbound",
    customersPipeline: "Pipeline",
    customersAccounts: "Accounts",
    customersAfterSales: "After-sales",
    customersChurn: "Churn & dormant",
    customersLead: "Prospects through customers. Send and won handoff require approval.",
    customersLockedLead:
      "Customer management is off until Sales or Customer Success module is enabled.",
    customersSalesGrace: "Sales agents are on but the Sales module is not imported yet.",
    customersModuleLocked: "The module for this view is off.",
    customersAskSteward: "Ask Steward",
    customersCampaigns: "Outbound campaigns",
    customersActiveCampaigns: (active: number, total: number) =>
      `${active} active / ${total} total`,
    customersCoverage: (pct: number) => `Contact coverage ${pct}%`,
    customersNoAlerts: "No alerts right now.",
    customersOpenDeals: "Open deals",
    customersPipelineDeals: "Deal pipeline",
    customersAccountsList: "Accounts",
    customersPromoteInquiry: "Promote to deal",
    customersSetStage: "Update stage",
    customersSaveNextAction: "Save next action",
    customersNextActionLabel: "Next action",
    customersNextActionDueLabel: "Due",
    customersLostReasonLabel: "Lost reason",
    customersEditInPipeline: "Edit in pipeline",
    customersQualifiedPromote: "Qualified — promote to deal",
    customersAmbiguousMail: (n: number) =>
      `${n} ambiguous mail triage link(s). Resolve via CLI: orgos sales mail-link-resolve`,
    customersMailLinkCliHint: "Resolve ambiguous mail links with the CLI.",
    customersMergeCliHint: "Merge duplicate accounts via CLI: orgos sales account merge --from … --into …",
    customersPromoteDone: "Deal created. Open the pipeline to continue.",
    customersActionError: "Update failed.",
    customersPipelineSummary: (open: number, weightedMan: number) =>
      `${open} open · weighted ${weightedMan} (10k JPY)`,
    customersInquiryQueue: "Inquiry queue",
    customersInquirySummary: (open: number, total: number) =>
      `${open} open / ${total} total`,
    customersHealth: "Customer health",
    customersHealthSummary: (
      total: number,
      healthy: number,
      atRisk: number,
      critical: number,
    ) => `${total} accounts · healthy ${healthy} · at_risk ${atRisk} · critical ${critical}`,
    customersRenewals: "Renewals due",
    customersChurnSummary: "Churn & dormant",
    customersChurnCounts: (
      atRisk: number,
      critical: number,
      churned: number,
      dormant: number,
    ) =>
      `at_risk ${atRisk} · critical ${critical} · churned ${churned} · dormant ${dormant}`,
    customersChurnEvents: "Recent churn events",
    account: "Account",
    runs: "Run status",
    admin: "Budget admin",
    receiptIssue: "Issue receipt",
    receipt: "Receive receipt",
    secretary: "Secretary",
    steward: "Steward",
    agentList: "Agent list",
    agentListEmpty: "No agents are on yet.",
    agentListLead:
      "Steward and Secretary are default windows and cannot be turned off. Other agents can.",
    agentDeskSection: "Default windows",
    agentDeptSection: "Department agents",
    agentChainTitle: "Request and reporting lines",
    agentChainLead:
      "Internal requests go through Steward. Company data is rewritten only when the owner asks Steward directly.",
    agentDeskBadge: "Default window",
    agentDeskFixed: "Always on · cannot turn off",
    agentLaneSteward: "Owner-direct → orchestrates all agents",
    agentLaneSecretary: "Owner-direct → internal asks go via Steward",
    agentLaneViaSteward: "Requests go through Steward",
    reportsToLine: (label: string) => `Reports to ${label}`,
    agentSection: "Agents",
    agentSectionLead: "Turn use on or off. Required agents stay on.",
    agentSearchPlaceholder: "Search agents",
    moduleList: "Module list",
    moduleListEmpty: "No modules are on yet.",
    moduleListLead: "Modules that are on. Turning one off needs approval.",
    moduleInstalledSection: "Imported modules",
    moduleInstalledLead: "After import, turn the module on or off. On requires approval.",
    moduleSearchPlaceholder: "Search modules",
    agentAdd: "Add agent",
    agentAddLead: "Search agents that are not in use and add them.",
    agentAddEmpty: "There are no agents left to add.",
    agentAdded: "Added.",
    agentProposedAdd: "Add proposed. CEO should confirm in the Approvals tab.",
    agentPendingAdd: "Add pending approval (Approvals tab)",
    moduleAddTab: "Add module",
    moduleAddLead: "Import modules that are not installed yet. They start off.",
    moduleAdd: "Add",
    moduleAdding: "Adding…",
    moduleEmptyInstalled: "No modules have been imported yet.",
    moduleEmptyCatalog: "There are no modules left to add.",
    moduleNoMatch: "No matching modules.",
    agentNoMatch: "No matching agents.",
    toggleOn: "On",
    toggleOff: "Off",
    toggleAgent: (name: string) => `Use ${name}`,
    toggleModule: (name: string) => `Turn ${name} on`,
    agentLockedRequired: "Core agent — cannot turn off.",
    agentLockedOwnerDesk: "Owner’s default window — cannot turn off.",
    agentLockedModule: "Turn the bound module off first.",
    modulePendingOn: "Enable pending approval (Approvals tab)",
    modulePendingOff: "Disable pending approval (Approvals tab)",
    moduleProposedOn: "Enable requested. Confirm it in the Approvals tab.",
    moduleProposedOff: "Disable requested. Confirm it in the Approvals tab.",
    moduleProposedImport: "Add proposed. CEO should confirm in the Approvals tab.",
    modulePendingImport: "Add pending approval (Approvals tab)",
    readonlyToggles: "You do not have permission for this action.",
    chatLead: "Write a question and send it. The reply stays here.",
    message: "Message",
    sendPlaceholder: "⌘/Ctrl+Enter to send",
    send: "Send",
    notify: "Allow completion notifications",
    conversation: (title: string) => `${title} conversation`,
    loading: "Loading…",
    emptyChat: "No conversation yet.",
    emptyChatHint: "Send from the box above to start a history.",
    generating: "Generating a reply…",
    generatingCount: (n: number) => `Generating ${n} replies…`,
    feedbackLabel: "Rate this reply",
    feedbackGood: "Good",
    feedbackBad: "Bad",
    feedbackThanks: "Thanks — saved",
    faqServedBadge: "FAQ instant answer (no LLM)",
    faqSection: "FAQ index",
    faqBuild: "Rebuild FAQ index",
    faqBuilding: "Rebuilding…",
    faqBuilt: (n: number) => `FAQ index updated (${n} entries)`,
    faqBuildLead: "Q&A curated from Good ratings. Exact matches skip the LLM.",
    llmRouteLabel: "LLM",
    llmRouteAuto: "Auto (local first)",
    llmRouteLocalAny: "Local (any)",
    llmRouteCloudAny: "Cloud (any)",
    llmRouteGroupLocal: "Local",
    llmRouteGroupCloud: "Cloud",
    llmRouteStatusLoading: "Checking local LLM…",
    llmRouteStatusUnavailable: "Could not load workers",
    llmRouteStatusConnected: (name: string) => `${name} connected`,
    llmRouteStatusDisconnected: (name: string) => `${name} not connected`,
    llmRouteStatusNoLocal: "No local worker",
    workersLinkBefore: "LLM workers: ",
    workersLink: "Worker settings",
    cloudLinkBefore: "Paid cloud services: ",
    cloudLink: "Cloud connection",
    historyLinkBefore: "History length: ",
    historyLink: "History count",
    chatSettingsTitle: "Chat history settings",
    chatSettingsLead:
      "Conversations are stored on this device. Turns older than the limit are deleted.",
    mailSection: "Mail",
    mailSettingsPointer: "Sender address and Gmail connection live in company settings.",
    companySettingsLink: "Company settings",
    mailConnected: (email: string) => `Gmail connected (${email})`,
    mailNotConnected: "Gmail not connected",
    mailExpired: "The token has expired. Connect again.",
    mailFromName: "Sender name",
    mailFromEmail: "Sender address",
    mailProvider: "Delivery method",
    mailSmtpHost: "SMTP host",
    mailSmtpPort: "SMTP port",
    mailSecretsNote:
      "OAuth tokens are not handled here. SMTP / IMAP passwords are saved to the server-side secret store below.",
    hubTitle: "Witness Hub operations",
    hubBind: "bind",
    hubBindPublic: "public",
    hubBindLoopback: "loopback",
    hubBindAllowed: "public bind allowed",
    hubBindBlocked: "public bind blocked",
    hubTlsPresent: "present",
    hubTlsMissing: "missing",
    hubTlsExpires: "expires",
    hubTlsExpired: "expired",
    hubTlsPlacement:
      "Place certificates at deploy/witness-hub/tls/server.pem and server.key. Private keys are never uploaded from the browser — this view only verifies.",
    hubMetricsUp: "reachable",
    hubMetricsDown: "unreachable",
    hubReadyForRelay: "Ready for public relay",
    hubYes: "yes",
    hubNo: "no",
    platformTitle: "Platform operations",
    platformLead:
      "Platform operations only — not shown in tenant navigation (allowlisted via ORGOS_PLATFORM_OPERATORS).",
    platformFlags: "Shipping flags",
    platformCommunityEnv: "Community env",
    platformEnvShipped: "Shipped",
    platformEnvNotShipped: "Not shipped",
    platformEnvHowTo:
      "Set COMMUNITY_TENANT_MAIL_CONNECT_SHIPPED=1 on Community and redeploy.",
    esignTitle: "National eID signing",
    esignLead:
      "The card, reader and PIN stay on the signer's device. The console only moves containers and shows the SiVa indication.",
    esignServices: "Service status",
    esignSidecar: "digidoc4j sidecar",
    esignSidecarUp: "responding",
    esignUnset: "not configured",
    esignLiveOk: "live validation available",
    esignLiveMissing: "live validation needs a configured SiVa",
    esignNewCase: "New case",
    esignCaseTitle: "Title",
    esignCaseTitlePlaceholder: "e.g. Non-disclosure agreement",
    esignPdf: "PDF",
    esignCreate: "Create",
    esignCreated: "created",
    esignCases: "Cases",
    esignNoCases: "No cases yet.",
    esignStatus: "Status",
    esignPrepare: "Build skeleton",
    esignPrepared: "unsigned.asice built",
    esignAttach: "Attach signed",
    esignAttached: "signed container attached",
    esignVerify: "Validate with SiVa",
    esignVerified: "TOTAL-PASSED (completed)",
    esignNotVerified: "national validation incomplete",
    esignDigestMismatch: "the container does not carry the source PDF digest",
    esignSignOnDevice:
      "Sign with DigiDoc4 and your card, then pick the resulting .asice before attaching.",
    esignSignedContainer: "Signed .asice",
    esignPickPdf: "Pick a PDF.",
    esignPickAsice: "Pick a signed .asice.",
    esignTitleRequired: "Enter a title.",
    mailSecretsTitle: "SMTP / IMAP secrets",
    mailSecretsStored:
      "Stored in data/secrets/mail-secrets.env (gitignored, mode 0600). Values are never returned — only masked hints.",
    mailSecretsSave: "Save secrets",
    mailSecretSet: "Set",
    mailSecretUnset: "Not set",
    mailSmtpUser: "SMTP user",
    mailSmtpPassword: "SMTP password",
    mailImapHost: "IMAP host",
    mailImapUser: "IMAP user",
    mailImapPassword: "IMAP password",
    mailConnect: "Connect Gmail",
    mailDisconnect: "Disconnect",
    mailConnectOpen: "Finish connecting in Community",
    maxTurns: "Turns to keep",
    turns: (n: number) => `${n} turns`,
    save: "Save",
    saved: "Saved",
    savedPruned: (n: number) => `Saved (${n} threads trimmed to the new limit)`,
    backSteward: "Back to Steward",
    backSecretary: "Back to Secretary",
    approvalsLabel: "CEO approval inbox",
    approvalsTitle: "Approvals",
    approvalsLead: "Items that need the CEO to confirm.",
    approvalsEmpty: "Nothing waiting for approval.",
    previewLoading: "Loading the diff…",
    previewToggle: "Body",
    approving: "Working…",
    approveApply: "Approve and apply",
    ceoQuestionsTitle: "Questions for the CEO",
    ceoQuestionAnswer: "Submit answers",
    correspondencePendingTitle: "Outbound mail pending",
    correspondencePendingEmpty: "No drafts waiting to send.",
    correspondenceDryRun: "Send dry-run",
    correspondenceSend: "Send",
    brokerTransferTitle: "Transfer instruction",
    brokerTransferLead: "Account numbers are masked. Execute the transfer in online banking.",
    brokerFrom: "From account",
    brokerAmount: "Amount (JPY)",
    brokerPayee: "Payee",
    brokerReference: "Reference",
    brokerDryRun: "Dry-run",
    brokerWrite: "Save instruction",
    towerCardTitle: "Tower assignment",
    towerJudgmentOnly: "Needs judgment / approval.",
    towerAssigned: "Assigned",
    towerAssignee: "Assignee (employee)",
    towerDueDate: "Due date",
    towerConfirm: "Confirm assignment",
    companyEventsTitle: "Company events (open)",
    companyEventsEmpty: "No open events this month.",
    companyEventKind: "Kind",
    companyEventTitleField: "Title",
    companyEventCreate: "Create",
    companyEventClose: "Close",
    companyEventArchive: "Archive",
    companyEventVoid: "Void",
    companyEventVoidReason: "Void reason (required)",
    companyEventChainVerify: "Verify chain",
    companyEventChainOk: "Chain verification OK",
    companyEventChainNg: "Chain verification failed",
    companyEventIncludeClosed: "Show closed / voided",
    executiveNotifyLabel: "Desktop alerts for attention items",
    executiveNotifyHint: "Notify when attention items are pending",
    reject: "Reject",
    settlementPasskeyRequired: "A settlement PassKey (iPhone) must be registered first.",
    settlementPasskeySettingsLink: "Register iPhone in Settings",
    cloudTitle: "Cloud LLM connection",
    cloudLead:
      "For faster replies than a local LLM, set an OpenAI or Anthropic API key. Usage is billed by each provider.",
    cloudStep1: "1. Get an API key",
    cloudStep2: "2. Environment variables at Console start",
    cloudExampleOpenai: "Example (OpenAI):",
    cloudExampleClaude: "Example (Claude):",
    cloudRestart: "Restart Operator Console after changing these settings.",
    cloudNotes: "Notes",
    cloudNotesBody:
      "Follow data classification (L0–L3) and the Operator Policy for anything sent to the cloud. Do not include payroll, cost, or personal data.",
    adminTitle: "Budget admin",
    adminLead: "Operate departments, allocation, and outlook from deterministic data.",
    executiveTitle: "Executive home",
    executiveLead: "Attention, goal gaps, and delegated work.",
    executiveAttention: "Needs attention",
    executiveRunway: "Runway",
    executiveCash: "Cash",
    executiveKindCustomer: "Customer",
    executiveKindMail: "Mail",
    executiveKindScheduling: "Scheduling",
    executiveKindCeoQuestion: "CEO question",
    executiveKindApproval: "Approval",
    executiveKindWire: "Wire",
    executiveAttentionEmpty: "Nothing needs attention right now.",
    executiveGaps: "Goals and gaps",
    executiveGapsEmpty: "No KPI definitions.",
    executiveTargetMissing: "Not set",
    executiveWork: "Delegated work",
    executiveWorkEmployee: "Team",
    executiveWorkGuest: "External",
    executiveWorkAi: "AI",
    executiveWorkUnassigned: "Unassigned",
    executiveWorkEmpty: "No open work orders.",
    executiveAgentSummaries: "Agent summaries",
    executiveVariance: "Revenue variance",
    executiveRefresh: "Refresh",
    executiveAskSteward: "Ask Steward",
    executiveOpenApprovals: "Approvals",
    executiveOpenRuns: "Run status",
    executiveRagGreen: "On track",
    executiveRagAmber: "Watch",
    executiveRagRed: "Action",
    executiveRagUnknown: "Unknown",
    executiveGapActual: "Actual",
    executiveGapTarget: "Target",
    workersTitle: "LLM workers",
    workersLead: "Each chat can pick Auto, local, or cloud. Only the env var name is stored.",
    workersRunning: (inflight: number, queued: number) =>
      `Running ${inflight} · queued ${queued}`,
    workersQueue: "Queue",
    workersQueueLimit: "Queue limit",
    workersDelete: "Delete",
    workersManual: "+ Manual",
    workersNew: "New worker",
    budgetView: "Budget views",
    budgetPeople: "People",
    budgetOverview: "Allocation",
    budgetPlans: "Business plan",
    budgetOutlook: "Outlook",
    budgetPayroll: "Payroll",
    budgetSources: "Sources",
    budgetHistory: "History",
    close: "Close",
    onboardingReady: "Ready to use the ledger",
    onboardingNotReady: "Ledger setup is not complete yet",
    onboardingLead:
      "Company profile and the first journal entry are required before using the ledger. Passkey is required to sign in.",
    walletLanes: "Lanes",
    envelope: "Expense envelope",
    payrollMatch: "Match",
    payrollUnbooked: "Not booked",
    payrollCheck: "Needs review",
    personSwitch: "People",
    reloadFailed: "Refresh failed — the last view is still shown. ",
    retry: "Retry",
    envelopeSummary: "Envelope summary",
    envelopeAndActual: "Envelope and actuals",
    envelopeActual: "Actuals",
    remaining: "Remaining",
    noEnvelope: "This person has no personal expense envelope yet.",
    receiptIngest: "Receipt ingest",
    walletLoading: "Loading personal budget…",
    actualThrough: (month: string) => `Actuals through ${month}`,
    noActuals: "No actuals",
    fetched: (label: string) => `Fetched ${label}`,
    refreshing: " · refreshing",
    refresh: "Refresh",
    refreshingShort: "Refreshing",
    refetch: "Reload",
    justNow: "just now",
    secondsAgo: (n: number) => `${n}s ago`,
    minutesAgo: (n: number) => `${n}m ago`,
    hoursAgo: (n: number) => `${n}h ago`,
    notFetched: "Not fetched",
    checklist: "Checks",
    sevCritical: "Action needed",
    sevWarn: "Review",
    sevInfo: "Question",
    revisionTitle: "Optimistic concurrency token",
    envelopeOver: "Envelope exceeded",
    ingestTitle: "Ingest a receipt",
    ingestLead:
      "Paste a signed QR link or JSON from the issuing organization, pick a category, and settle.",
    splitAlloc: "Split across multiple accounts",
    splitAllocLegend: "Split allocation (total = receipt ",
    splitAllocClose: ")",
    splitFromQr: " · auto-filled from QR lines",
    categoryN: (n: number) => `Category ${n}`,
    amountYen: "Amount (yen)",
    removeRow: "Remove row",
    addRow: "Add row",
    category: "Category",
    qrPayload: "QR / signed payload",
    qrPlaceholder: "https://receipt.oorgos.org/r#v2z.… or JSON",
    ingesting: "Ingesting…",
    ingest: "Ingest",
    claims: "Claims",
    claimPendingReimburse: "Awaiting reimbursement",
    claimReimbursed: "Reimbursed",
    claimPosted: "Posted",
    claimPendingApproval: "Awaiting approval",
    claimApproved: "Approved",
    claimRejected: "Rejected",
    wireSent: "Wire sent",
    wireFailed: "Wire failed (claim continues)",
    wireSkipped: "Wire skipped",
    wireReady: "Wire eligible",
    wireNone: "No Wire",
    invoiceFormatOnly: "T-number:format_only",
    invoiceVerified: "T-number:verified",
    lateSubmit: (days: string) => `submitted ${days} days later`,
    progressIngest: "Progress: ingest",
    progressPendingApproval: " → awaiting approval",
    progressRejected: " → rejected",
    progressApproved: " → approved",
    progressPostedPending: " → posted → awaiting reimbursement",
    progressReimbursed: " → posted → reimbursed",
    reasonPrefix: " · reason: ",
    categories: "Categories",
    categoriesTable: "Category envelope, actuals, and remaining",
    colCategory: "Category",
    colEnvelope: "Envelope",
    colActual: "Actuals",
    colRemaining: "Remaining",
    accountMeeting: "5730 Meetings",
    accountEntertainment: "5710 Entertainment",
    accountTravel: "5720 Travel",
    syncUpdatedElsewhere: "Budget updated in another view (reloaded)",
    syncFromAdmin: "Applied changes from budget admin",
    syncBudgetUpdated: "Budget data was updated",
    ingestNeedDept: "Department and receipt payload are required",
    ingestSplitNeedTwo: "Split allocation needs two or more rows, each with a positive amount",
    ingestSplitMismatch: (total: number, expected: number) =>
      `Split total ${total} does not match the receipt total ${expected}`,
    ingestDone: "Ingested",
    ingestConflict:
      "Another operator updated this claim first. Latest data was reloaded. Review and ingest again.",
    ingestBlockedDept:
      " — increase the department envelope from Allocation in budget admin first",
    gateAllowImmediate: "Within envelope · immediate settlement",
    gateNeedsManager: "Manager approval required",
    gateNeedsRep: "Representative approval required",
    gateNeedsLate: "Late-exception approval required",
    gateNeedsRingi: "Ringi approval required (REG-004)",
    gateNeedsBoard: "Board evidence required (REG-004 C)",
    gateBlockedDept: "Department envelope short (Allocation first)",
    gateBlockedCompany: "Company envelope short",
    gateShortAllow: "In envelope",
    gateShortManager: "Manager",
    gateShortRep: "Representative",
    gateShortLate: "Late exception",
    gateShortRingi: "Ringi",
    gateShortBoard: "Board",
    gateShortDept: "Dept short",
    gateShortCompany: "Company short",
    claimApprovalsTitle: "Expense claims",
    claimApprovalsEmpty: "No claims waiting for approval.",
    claimWho: "Claimant",
    claimAmount: "Amount",
    claimRemaining: "Envelope left",
    claimDueOn: "Pay-back date",
    claimApproveWithDue: "Approve and set the pay-back date",
    claimSendBack: "Send back",
    claimApproving: "Working…",
    claimCoApprover: "Second approver",
    claimBoardEvent: "Board record",
    claimNeedCoApprover: "This amount needs a second approver.",
    claimNeedBoardEvent: "This amount needs a board record.",
    claimSelectPlease: "Please choose",
    claimDeskTitle: "Expense claim",
    claimDeskLead:
      "Scan the receipt QR and send it. The pay-back date shows up here.",
    claimDeskRemaining: "Left to spend",
    claimDeskCategory: "What it was for",
    claimDeskScan: "Scan QR",
    claimDeskStopScan: "Stop scanning",
    claimDeskNoCamera:
      "This device cannot scan. Paste the QR text instead.",
    claimDeskPaste: "Paste QR text",
    claimDeskSubmit: "Send",
    claimDeskSubmitting: "Sending…",
    claimDeskDone: "Sent.",
    claimDeskMine: "My claims",
    claimDeskEmpty: "No claims yet.",
    claimDeskWaiting: "Waiting",
    claimDeskPassed: "Approved",
    claimDeskSentBack: "Sent back",
    claimDeskBackOn: (date: string) => `Back on ${date}`,
    claimDeskBackUnset: "The pay-back date is set at approval",
    claimDeskNoEnvelope:
      "You have no envelope yet. Ask your manager to set one.",
    claimDeskScanning: "Point the camera at the QR code",
    claimDeskCameraDenied: "The camera is unavailable. Paste the QR text instead.",
    claimDeskSignOut: "Sign out",
    payrollCompanyTitle: "Payroll (company)",
    payrollEmpty: "No payroll data.",
    payrollNonePerson: (name: string) => `${name} has no payroll assignment.`,
    payrollNoneGeneric: "No payroll assignment.",
    payrollKindOfficer: "Officer compensation",
    payrollKindEmployee: "Salary",
    payrollKindNone: "Out of scope",
    payrollReconcile: "Reconcile",
    payrollExpected: "Expected",
    payrollBooked: "Booked",
    payrollVariance: "Variance",
    payrollOfficerMonthly: "Officers (monthly)",
    payrollEmployeeMonthly: "Employees (monthly)",
    payrollOfficers: "Officers",
    payrollMonthly: "Monthly",
    payrollMonthlyAmount: "Monthly amount",
    payrollExpectedCum: "Expected to date",
    payrollBookedCum: "Booked to date",
    yen: "yen",
    workersCloudOverflow: "Cloud overflow",
    workersWaitThreshold: "Wait threshold (ms)",
    workersTable: "Workers",
    workersColStatus: "Status",
    workersColName: "Name",
    workersColKind: "Kind",
    workersColModel: "Model",
    workersColConcurrent: "Concurrency",
    workersColKeyEnv: "Key env",
    workersColEnabled: "Enabled",
    workersProbe: "Probe",
    workersNewLabel: "New worker",
    commandFallback: "Command",
    commandFailed: "The command failed",
    commandHumanGate:
      "Human gate. Run this from Wire, transfer, or approval UI.",
    commandRun: "Run",
    commandRerun: "Run again",
    budgetValidating: "Validating the budget source…",
    budgetLoadFailed: "Could not load budget data",
    budgetLoadHint: "Check the network and authentication, then retry.",
    companyUnset: "Company budget is not set",
    companyUnsetTip: "Register the fiscal year and company envelope to start.",
    expenseBudget: "Expense budget",
    revenueBudget: "Revenue budget",
    unset: "Not set",
    companyBudgetYen: "Company budget (yen)",
    companyBudgetSet: "Company budget set",
    startFromPlan: "Start from the business plan",
    fiscalYear: "Fiscal year",
    planApprovedFix: "Approved · fixed",
    planApproved: "Approved",
    planPending: "Awaiting approval",
    planDraft: "Draft",
    monthShort: (n: number) => {
      const names = [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
      ];
      return names[n - 1] ?? String(n);
    },
    subtotal: "Subtotal",
    officerPayrollSubtotal: "Officer + payroll subtotal",
    corporateSubtotal: "Corporate subtotal",
    businessUnit: "Business unit",
    corporateExpense: "Shared corporate expense",
    colAccount: "Account",
    colAmount: "Amount",
    total: "Total",
    none: "None",
    revenueBreakdown: "Revenue breakdown",
    expenseBreakdown: "Expense breakdown",
    corporateCommon: "Company-wide",
    sourcesTip: "Do not edit these files from this screen.",
    recordCount: (n: number) => `${n} records`,
    noHistory: "No history yet.",
    conflictOther:
      "Another operator updated first. Latest data was reloaded. Review and try again.",
    retriedLatest: (message: string) => `${message} (retried with the latest data)`,
    syncFromOther: "Applied a budget update from another view",
    syncReloaded: "Reloaded the latest budget",
    envelopeProposal: (suggested: string, current: string | null) =>
      current
        ? `Envelope proposal ${suggested} (current ${current})`
        : `Envelope proposal ${suggested}`,
    midOutlook: "In-period outlook",
    outlookOpex: "Outlook (opex)",
    outlookProfitTip: (amount: string) =>
      `Profit proxy ${amount} (revenue − opex − depreciation)`,
    plan: "Plan",
    outlookActualThrough: (label: string) => `Actuals (through ${label})`,
    vsPlan: "Vs plan",
    vsPlanTip:
      "Outlook opex minus approved plan opex. Positive means the plan is likely to be exceeded.",
    outlookOverEnvelope:
      "Outlook opex exceeds the spending envelope. Change the envelope on the Allocation tab.",
    deptOutlookGap: (delta: string) =>
      `Department total and company outlook differ (delta ${delta}).`,
    monthlyOpex: "Monthly (opex)",
    showMoreMonths: "Also show revenue, capex, depreciation",
    colMonth: "Month",
    colRole: "Kind",
    roleTip: "Actual is a closed month. Forecast is the remaining months.",
    opex: "Opex",
    revenue: "Revenue",
    capex: "Capex",
    depreciation: "Depreciation",
    actual: "Actual",
    forecast: "Forecast",
    deptOutlook: "Department outlook (opex)",
    department: "Department",
    deptOutlookOpex: "Opex outlook",
    editForecast: "Edit forecast",
    outlookInited: "Outlook initialized",
    init: "Initialize",
    outlookSynced: "Remaining months synced from budget vs actual (republish)",
    syncFromYojitsu: "Sync from budget vs actual",
    proposalComputed: "Envelope proposal calculated",
    proposal: "Proposal",
    proposalNote: (suggested: string, current: string, delta: string) =>
      `Envelope proposal ${suggested} (current ${current} · delta ${delta}). It does not change automatically. Edit on the Allocation tab.`,
    needAsOf: "Enter the as-of month",
    asOfUpdated: (month: string) => `As-of month set to ${month}`,
    asOfMonth: "As-of month",
    asOfTip: "Months through here are actuals. Later months are forecast.",
    needTargetMonth: "Enter the target month",
    monthSaved: (month: string) => `Saved outlook for ${month}`,
    targetMonth: "Target month",
    targetMonthTip: "The month to put a forecast in. Pick one from the list.",
    needApprover: "Select an approver",
    outlookPublished: "Outlook published",
    publisher: "Approver",
    publisherTip:
      "Pick someone other than the editor (CEO or department head). Names come from the org chart. Secretary and agents cannot be selected.",
    selectPlease: "Select",
    publish: "Publish",
    noOtherApprover:
      "No other department head can approve (self-approval is blocked). Register an approver role in operators.",
    businessPlan: "Business plan",
    businessPlanTip: "Revenue and opex plan reference. Allocate on the Allocation tab.",
    businessPlanAmount: (amount: string) => `Business plan ${amount}`,
    mismatch: " · mismatch",
    operatingProfit: "Operating profit",
    operatingProfitTip:
      "P&L operating-profit plan (business-plan). Before corporate tax. Not profit before tax. Interest expense is in SGA for this tenant.",
    capexEquipment: "Capex (equipment)",
    sgaPlan: (amount: string) => `SGA ${amount}`,
    openaiCompat: "OpenAI-compatible",
    localKeyOptional: "Local key optional",
    envReady: "env configured",
    keyInEnv: "Set the key in .env",
    presets: "Presets",
    presetExists: "Same kind already exists (you can still add)",
    monthSelect: "Select month",
  },
);
