#!/usr/bin/env node
/**
 * Scaffold a catalog-only module test file.
 * Usage: npm run test:registry:scaffold -- clinic
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";
import { getModuleSeedDir } from "../src/lib/modules.js";
import {
  assertCatalogFileMapCoversReadiness,
  buildCatalogFileMap,
  buildRegistryFromDisk,
  TEST_REGISTRY_PATH,
} from "../tests/test-registry.js";

const catalogId = process.argv[2];
if (!catalogId) {
  console.error("Usage: npm run test:registry:scaffold -- <catalog_id>");
  process.exit(1);
}

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const readinessPath = join(root, "steward/modules/readiness.yaml");
const readiness = YAML.parse(readFileSync(readinessPath, "utf-8")) as {
  modules: Record<string, { tier: string }>;
};

if (!readiness.modules[catalogId]) {
  console.error(`Unknown catalog id "${catalogId}" — not in steward/modules/readiness.yaml`);
  process.exit(1);
}

const map = buildCatalogFileMap();
if ([...Object.values(map).flat()].includes(catalogId)) {
  console.error(`Catalog id "${catalogId}" already mapped in test registry`);
  process.exit(1);
}

const kebab = catalogId.replace(/_/g, "-");
const relPath = join("tests", "catalog", `${kebab}.test.ts`);
const absPath = join(root, relPath);
const validatorPath = join(getModuleSeedDir(catalogId), "validate.ts");

if (existsSync(absPath)) {
  console.error(`Test file already exists: ${relPath}`);
  process.exit(1);
}
if (!existsSync(validatorPath)) {
  console.error(`Create the module validator first: ${validatorPath}`);
  process.exit(1);
}

const body = `import { describeCatalogModule } from "./catalog-module-harness.js";

describeCatalogModule("${catalogId}");
`;

writeFileSync(absPath, body);
const registry = buildRegistryFromDisk();
writeFileSync(
  TEST_REGISTRY_PATH,
  `# OrgOS test registry — generated by npm run test:registry:sync\n# Do not hand-edit tests: section; edit test-registry.ts rules or catalog modules.\n\n${YAML.stringify(registry, { lineWidth: 120 })}`
);
console.log(`Created ${relPath.replace(/\\/g, "/")}`);
console.log(`Updated ${TEST_REGISTRY_PATH}`);
console.log("Next: npm run test:registry:check");

const issues = assertCatalogFileMapCoversReadiness();
if (issues.length) {
  console.warn("Readiness modules still without tests:", issues.join("; "));
}
