#!/usr/bin/env node
/**
 * Regenerate tests/test-registry.yaml from disk + classification rules.
 * Usage: npm run test:registry:sync
 */
import { readFileSync, writeFileSync } from "node:fs";
import { buildRegistryFromDisk, TEST_REGISTRY_PATH } from "../tests/test-registry.js";
import YAML from "yaml";
import { join } from "node:path";

const registry = buildRegistryFromDisk();
const doc = YAML.stringify(registry, { lineWidth: 120 });
writeFileSync(TEST_REGISTRY_PATH, `# OrgOS test registry — generated by npm run test:registry:sync\n# Do not hand-edit tests: section; edit test-registry.ts rules or catalog_modules.\n\n${doc}`);

const testingModulesPath = join(import.meta.dirname, "../steward/rules/testing-modules.md");
const coverage = Object.values(registry.catalog_modules).map((entry) => entry.coverage_tier);
const fullCount = coverage.filter((tier) => tier === "full").length;
const dedicatedOnlyCount = coverage.filter((tier) => tier === "dedicated").length;
let testingModules = readFileSync(testingModulesPath, "utf-8");
testingModules = testingModules
  .replace(
    /(\|\s*Vitest テストファイル\s*\|\s*\*\*)\d+(\*\*)/,
    `$1${registry.stats.vitest_total}$2`
  )
  .replace(
    /(静的 `it`\/`test` \*\*)\d+(\*\*)/,
    `$1${registry.stats.static_test_cases}$2`
  )
  .replace(
    /(\|\s*CLI 登録（`MODULE_CLI_BUNDLES`）\s*\|\s*\*\*)\d+(\*\*)/,
    `$1${registry.stats.catalog_cli_registered}$2`
  )
  .replace(
    /(\|\s*catalog coverage gap\s*\|\s*\*\*)\d+(\*\*)/,
    `$1${registry.stats.catalog_gap}$2`
  )
  .replace(
    /(\|\s*catalog dedicated \(\+ full\)\s*\|\s*\*\*)\d+(\*\*)/,
    `$1${registry.stats.catalog_dedicated}$2`
  )
  .replace(
    /(\|\s*catalog bundled\s*\|\s*\*\*)\d+(\*\*)/,
    `$1${registry.stats.catalog_bundled}$2`
  )
  .replace(
    /(\|\s*catalog_only\s*\|\s*\*\*)\d+(\*\*)/,
    `$1${registry.stats.catalog_only}$2`
  )
  .replace(
    /(\|\s*full\s*\|\s*)\d+(\s*\|)/,
    `$1${fullCount}$2`
  )
  .replace(
    /(\|\s*dedicated\s*\|\s*)\d+(\s*\|)/,
    `$1${dedicatedOnlyCount}$2`
  );
writeFileSync(testingModulesPath, testingModules);

const frameworkAssessmentPath = join(import.meta.dirname, "../docs/framework-assessment.md");
let frameworkAssessment = readFileSync(frameworkAssessmentPath, "utf-8");
frameworkAssessment = frameworkAssessment.replace(
  /(\*\*~95\/100\*\*（[^·]+· \*\*)\d+(\s+tests\*\*)/,
  `$1${registry.stats.static_test_cases}$2`
);
writeFileSync(frameworkAssessmentPath, frameworkAssessment);

console.log(
  `Wrote ${TEST_REGISTRY_PATH}, ${testingModulesPath}, and ${frameworkAssessmentPath} (${registry.stats.vitest_total} tests)`
);
