#!/usr/bin/env node
/**
 * Regenerate tests/test-registry.yaml from disk + classification rules.
 * Usage: npm run test:registry:sync
 */
import { writeFileSync } from "node:fs";
import { buildRegistryFromDisk, TEST_REGISTRY_PATH } from "../tests/test-registry.js";
import YAML from "yaml";

const registry = buildRegistryFromDisk();
const doc = YAML.stringify(registry, { lineWidth: 120 });
writeFileSync(TEST_REGISTRY_PATH, `# OrgOS test registry — generated by npm run test:registry:sync\n# Do not hand-edit tests: section; edit test-registry.ts rules or catalog_modules.\n\n${doc}`);
console.log(`Wrote ${TEST_REGISTRY_PATH} (${registry.stats.vitest_total} tests)`);
