/** Jurisdiction-pack modules — steward/jurisdiction-packs/{code}/modules/{id}/ */
export const JP_PACK_MODULE_IDS = [
  "jp_carbon_neutral_2050",
  "jp_women_empowerment",
  "jp_privacy_policy",
  "jp_subsidy_application",
  "jp_trademark_application",
  "jp_corporate_registration",
  "jp_medical_device",
  "jp_cosmetics_mah",
  "jp_permit_registry",
  "jp_permit_application",
  "jp_minpaku",
  "jp_certification",
  "jp_jsox",
  "jp_inspection",
  "jp_bank_corporate",
  "jp_tax_corporate",
  "jp_tax_consumption",
  "jp_consumption_refund",
  "jp_invoice_qualified",
  "jp_withholding_statutory",
  "jp_payroll",
  "jp_social_insurance",
  "jp_statutory_meetings",
  "jp_employment_rules",
  "jp_labor_contract",
  "jp_subcontractor_act",
  "jp_data_breach",
  "jp_visa_employment",
  "jp_takken",
  "jp_patent_application",
] as const;

export type JpPackModuleId = (typeof JP_PACK_MODULE_IDS)[number];
