import { defineCopy } from "@ops-shared/define-copy";

export const WIRE_COPY = defineCopy(
  {
    folders: "フォルダ",
    waitingOurs: "承認待ち",
    waitingTheirs: "相手送信待ち",
    noTenants: "表示できる組織がありません",
    noTenantsHint: "Wire 用のテナント設定を確認してください。",
    tenants: "テナント",
    integrityOk: "整合性 OK",
    needsReview: "要確認",
    waitingOursCount: (n: number) => `承認待ち ${n}`,
    waitingTheirsCount: (n: number) => `相手送信待ち ${n}`,
    refresh: "更新",
    compose: "新規作成",
    loading: "読み込み中…",
    emptyOurs: "承認待ちはありません",
    emptyTheirs: "相手からの返信待ちはありません",
    emptyOursHint: "新しい通知は「新規作成」から送れます。",
    emptyTheirsHint: "送った通知への返答がここに並びます。",
    opsPanel: "配送・公証（オペレータ向け）",
    counterparty: (label: string) => `相手方: ${label}`,
    contract: (id: string) => ` · 契約 ${id}`,
    thisFolder: "このフォルダ:",
    approvals: "承認",
    waitingBadge: (n: number) => `待ち ${n}`,
    colNumber: "番号",
    colStatus: "状態",
    colPeer: "相手",
    colContract: "契約",
    colNotice: "通知",
    colKind: "種類",
    colTxn: "取引",
    colDirection: "向き",
    colSummary: "要約",
    colOrigin: "由来",
    pickNotice: "通知を選ぶ",
    pickNoticeHint: "左の一覧から開くと、承認や配送ができます。",
    needCoApprover: "tier B の共同承認者を選択してください",
    approved: "承認しました",
    rejectReason: "Wire Console から差し戻し",
    rejected: "差し戻しました",
    delivered: "相手組織へ送信しました",
    deliverWaiting: "送信を待機しています",
    witnessOk: (matched: number, required: number) =>
      `公証を登録しました（${matched}/${required}）`,
    witnessPartial: (left: number) => `公証を登録しました。残り ${left} 件`,
    witnessEnough: (matched: number, required: number) =>
      `公証は十分です（${matched}/${required}）`,
    witnessShort: (matched: number, required: number) =>
      `公証が不足しています（${matched}/${required}）`,
    from: "差出人",
    to: "宛先",
    when: "日時",
    coApprover: "共同承認者（tier B）",
    selectPlease: "選択してください",
    approve: "承認",
    reject: "差し戻し",
    send: "送信",
    witnessSent: "公証を登録（送信側）",
    witnessReceived: "公証を登録（受信側）",
    witnessVerify: "公証を確認",
    systemInfo: "システム情報（開発者向け）",
    composeTitle: "新規作成",
    close: "閉じる",
    composeTo: "宛先",
    composeKind: "種別",
    composeContract: "契約 ID",
    composeEvent: "関連イベント ID",
    composeEventPh: "uuid（返信時）",
    composeBody: "本文",
    sending: "送信中…",
    sendRequest: "送信申請",
    created: (id: string) => `作成しました: ${id}`,
    noThreads: "スレッドがありません",
    messageCount: (n: number) => `${n} 件`,
    noticeContractExec: "契約履行の通知",
    noticeObligation: "義務の受理",
    noticeInvoice: "請求書の発行",
    noticePayment: "支払いの指示",
    noticeContractDone: "契約の締結",
    dashboardRefresh: "更新",
    validationOk: "整合性 OK",
    outbox: (n: number) => `送信箱 ${n}`,
    inbox: (n: number) => `受信箱 ${n}`,
    txns: (n: number) => `取引 ${n}`,
    wirePending: (n: number) => `未送信 ${n}`,
    witnessPending: (n: number) => `未公証 ${n}`,
    witnessHubs: (n: number) => `公証ハブ ${n}`,
    outboxTitle: "送信箱",
    outboxEmpty: "送信箱は空です",
    inboxTitle: "受信箱",
    inboxEmpty: "受信箱は空です",
    deliveryTitle: "配送",
    pendingDelivered: (pending: number, delivered: number) =>
      `未送信 ${pending} · 送信済 ${delivered}`,
    flushPending: "未送信を処理",
    peerId: "相手 ID",
    eventId: "イベント ID",
    flushedDeliveries: (n: number) => `未送信 ${n} 件を処理しました`,
    deliveredOk: (reason: string) => `送信しました（${reason}）`,
    queuedSkipped: (reason: string) => `待機 / スキップ（${reason}）`,
    witnessTitle: "公証",
    hubsMode: (n: number, mode: string) => `${n} ハブ · ${mode}`,
    disabled: "オフ",
    verifyEvent: "イベントを確認",
    side: "向き",
    sideSent: "送信側",
    sideReceived: "受信側",
    registerAttestation: "公証を登録",
    flushedWitness: (n: number) => `公証 ${n} 件を処理しました`,
    registeredQuorum: (matched: number, required: number, ok: boolean) =>
      `登録 · 定足数 ${matched}/${required} ${ok ? "OK" : "待ち"}`,
    verifyQuorum: (
      receipts: number,
      matched: number,
      required: number,
      ok: boolean,
    ) =>
      `領収 ${receipts} · 定足数 ${matched}/${required} ${ok ? "OK" : "不足"}`,
    pendingWitnessCount: (n: number) => `公証待ち ${n} 件`,
    proposeTitle: "通知の起案",
    proposing: "起案中…",
    propose: "起案",
  },
  {
    folders: "Folders",
    waitingOurs: "Awaiting approval",
    waitingTheirs: "Waiting on the other party",
    noTenants: "No organizations to show",
    noTenantsHint: "Check the Wire tenant configuration.",
    tenants: "Tenants",
    integrityOk: "Integrity OK",
    needsReview: "Needs review",
    waitingOursCount: (n: number) => `Awaiting approval ${n}`,
    waitingTheirsCount: (n: number) => `Waiting on counterpart ${n}`,
    refresh: "Refresh",
    compose: "Compose",
    loading: "Loading…",
    emptyOurs: "Nothing awaiting approval",
    emptyTheirs: "Nothing waiting on the other party",
    emptyOursHint: "Send a new notice from Compose.",
    emptyTheirsHint: "Replies to sent notices appear here.",
    opsPanel: "Delivery and witness (operators)",
    counterparty: (label: string) => `Counterparty: ${label}`,
    contract: (id: string) => ` · contract ${id}`,
    thisFolder: "This folder:",
    approvals: "Approvals",
    waitingBadge: (n: number) => `Waiting ${n}`,
    colNumber: "No.",
    colStatus: "Status",
    colPeer: "Peer",
    colContract: "Contract",
    colNotice: "Notice",
    colKind: "Kind",
    colTxn: "Transaction",
    colDirection: "Direction",
    colSummary: "Summary",
    colOrigin: "Origin",
    pickNotice: "Select a notice",
    pickNoticeHint: "Open one from the list to approve or deliver.",
    needCoApprover: "Select a tier B co-approver",
    approved: "Approved",
    rejectReason: "Returned from Wire Console",
    rejected: "Returned",
    delivered: "Sent to the counterpart organization",
    deliverWaiting: "Waiting to send",
    witnessOk: (matched: number, required: number) =>
      `Witness registered (${matched}/${required})`,
    witnessPartial: (left: number) =>
      `Witness registered. ${left} remaining`,
    witnessEnough: (matched: number, required: number) =>
      `Witness quorum met (${matched}/${required})`,
    witnessShort: (matched: number, required: number) =>
      `Witness quorum short (${matched}/${required})`,
    from: "From",
    to: "To",
    when: "When",
    coApprover: "Co-approver (tier B)",
    selectPlease: "Select",
    approve: "Approve",
    reject: "Return",
    send: "Send",
    witnessSent: "Register witness (sent)",
    witnessReceived: "Register witness (received)",
    witnessVerify: "Verify witness",
    systemInfo: "System details (developers)",
    composeTitle: "Compose",
    close: "Close",
    composeTo: "To",
    composeKind: "Kind",
    composeContract: "Contract ID",
    composeEvent: "Related event ID",
    composeEventPh: "uuid (when replying)",
    composeBody: "Body",
    sending: "Sending…",
    sendRequest: "Submit to send",
    created: (id: string) => `Created: ${id}`,
    noThreads: "No threads",
    messageCount: (n: number) => `${n}`,
    noticeContractExec: "Contract performance notice",
    noticeObligation: "Obligation acknowledged",
    noticeInvoice: "Invoice issued",
    noticePayment: "Payment instructed",
    noticeContractDone: "Contract executed",
    dashboardRefresh: "Refresh",
    validationOk: "Integrity OK",
    outbox: (n: number) => `Outbox ${n}`,
    inbox: (n: number) => `Inbox ${n}`,
    txns: (n: number) => `Transactions ${n}`,
    wirePending: (n: number) => `Unsent ${n}`,
    witnessPending: (n: number) => `Unwitnessed ${n}`,
    witnessHubs: (n: number) => `Witness hubs ${n}`,
    outboxTitle: "Outbox",
    outboxEmpty: "Outbox is empty",
    inboxTitle: "Inbox",
    inboxEmpty: "Inbox is empty",
    deliveryTitle: "Delivery",
    pendingDelivered: (pending: number, delivered: number) =>
      `pending ${pending} · delivered ${delivered}`,
    flushPending: "Flush pending",
    peerId: "Peer ID",
    eventId: "Event ID",
    flushedDeliveries: (n: number) => `Flushed ${n} pending delivery(ies)`,
    deliveredOk: (reason: string) => `Delivered (${reason})`,
    queuedSkipped: (reason: string) => `Queued / skipped (${reason})`,
    witnessTitle: "Witness",
    hubsMode: (n: number, mode: string) => `${n} hub(s) · ${mode}`,
    disabled: "Off",
    verifyEvent: "Verify event",
    side: "Side",
    sideSent: "Sent",
    sideReceived: "Received",
    registerAttestation: "Register attestation",
    flushedWitness: (n: number) => `Flushed ${n} witness attestation(s)`,
    registeredQuorum: (matched: number, required: number, ok: boolean) =>
      `Registered · quorum ${matched}/${required} ${ok ? "OK" : "pending"}`,
    verifyQuorum: (
      receipts: number,
      matched: number,
      required: number,
      ok: boolean,
    ) =>
      `${receipts} receipt(s) · quorum ${matched}/${required} ${ok ? "OK" : "FAIL"}`,
    pendingWitnessCount: (n: number) => `${n} witness attestation(s) pending`,
    proposeTitle: "Propose notice",
    proposing: "Proposing…",
    propose: "Propose",
  },
);
